### ISSUE TITLE
Eliminate all instances when Pulp writes to /tmp and always use the worker working directory

### ISSUE THREAD

**Issue by fao89** [pulp/pulpcore#2061]
Author: @goosemania (ttereshc)

Redmine Issue: 9569, https://pulp.plan.io/issues/9569

---

There were various issues due to Pulp writing to /tmp, mostly it's running out of disc space because /tmp is usually not expected to be large.  
Problems come from `NamedTemporaryFile` and `TemporaryDirectory` which do not have `dir` parameter specified.

There is also inconsistency in how directories are referred to.  
Let's fix it as well.  
Current flavours for the current directory are `dir="."` and `dir=os.getcwd()`.

It would be good to check plugins as well, I just fixed 4 places in pulp_rpm.

**Comment by gerrod3** [comment]
Looked around this repository and found some instances in import.py, importexport.py and factory.py
