### ISSUE TITLE
Users running into timeouts with error messages that are unhelpful

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulpcore#2169]
Originally posted by dalley
https://pulp.plan.io/issues/9301

See attached bugzilla.

There was some additional discussion with a separate upstream user, who was running into this same issue: https://riot.im/app/#/room/#pulp:matrix.org/$xyV5D40cKUjqOYK7n7fk3J8v1RAqsu1KfafcYl968v8

The user had hypothesized that that maybe the "retries" were all counting towards the same "total timeout", but we have no confirmation of this.

This upstream aiohttp issue includes the same traceback and might provide some insight: https://github.com/aio-libs/aiohttp/issues/5239#issuecomment-727544671

I did also notice that we use the same ClientSession for all of a downloader's requests, that might be relevant: https://github.com/pulp/pulpcore/blob/master/pulpcore/download/http.py#L161-L163

**Comment by mdellweg** [comment]
This was transferred to allow a backport. I think we can close it.

**Comment by bmbouter** [comment]
@dralley do you know if this is still an issue?

**Comment by dralley** [comment]
It's not clear.  There is this BZ which may or may not be related https://bugzilla.redhat.com/show_bug.cgi?id=2043149

**Comment by bmbouter** [comment]
That BZ is closed, and I'm inclined to close this one also without additional input that clearly states there is more work to be done. Please comment or reopen if you believe there is something that should be done.
