### ISSUE TITLE
Deprecate `ACCESS_POLICY_VIEWSET_NAME` from models

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#2209]
While developing https://github.com/pulp/pulpcore/pull/2198/files we realized we already have `pulpcore.app.utils.get_viewset_for_model` that can find the viewset from a model without this attribute. It's no longer in-use and for clarity should no longer be defined.

This issue is to produce a deprecation warning if it's defined.

**Comment by jjg-dressipi** [comment]
This makes the [DailyWTF](https://thedailywtf.com/articles/the-base-model)!

**Comment by dralley** [comment]
I wish they had provided a more honest description. https://thedailywtf.com/articles/comments/the-base-model/1#comment-579816
