### ISSUE TITLE
django-guardian plugin cause perfomance issues on large number of objects 

### ISSUE THREAD

**Issue by AvoidMe** [pulp/pulpcore#2216]
**Version**
`pulpcore-3.17.3`
`pulp_rpm-3.17.3`
`pulp_ansible-0.12.0`
`pulp_container-2.10.0`
`pulp_deb-2.17.0`
`pulp_file-1.10.1`
`pulp_python-3.6.0`

**Describe the bug**
We have a single-user (admin) pulp with a lot of small rpm/file repositories.  `guardian_userobjectpermission` table has 4kk records:
```
pulp=# SELECT COUNT(*) FROM guardian_userobjectpermission WHERE guardian_userobjectpermission.user_id=1;
  count  
---------
 4119969
(1 row)
```
We have a big number of small tasks running all the time (like 50k per day), at some point our queue became bigger and increasing workers count doesn't help. Every task was completed in less than ~1-5 seconds, but waiting for new task / saving task results takes 30/40 seconds, also, CPU on PostgreSQL server went 100%.
After a lot of research, we found out what this query took around 20-30 seconds to execute:
```
SELECT DISTINCT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" LEFT OUTER JOIN "guardian_userobjectpermission" ON ("auth_user"."id" = "guardian_userobjectpermission"."user_id") WHERE (("guardian_userobjectpermission"."content_type_id" = 18 AND "guardian_userobjectpermission"."object_pk" = 'b73795aa-0c95-4429-8372-4f6f80171ae2') OR EXISTS(SELECT (1) AS "a" FROM "core_userrole" V0 INNER JOIN "core_role" V1 ON (V0."role_id" = V1."pulp_id") INNER JOIN "core_role_permissions" V2 ON (V1."pulp_id" = V2."role_id") WHERE (V2."permission_id" IN (SELECT U0."id" FROM "auth_permission" U0 WHERE U0."content_type_id" = 18) AND (V0."object_id" IS NULL OR (V0."content_type_id" = 18 AND V0."object_id" = 'b73795aa-0c95-4429-8372-4f6f80171ae2')) AND V0."user_id" = "auth_user"."id") LIMIT 1)) ORDER BY "auth_user"."id" ASC LIMIT 1
```
After disabling `guardian.backends.ObjectPermissionBackend` in pulp settings.py, everything went back to normal
```
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # "guardian.backends.ObjectPermissionBackend",
    "pulpcore.backends.ObjectRolePermissionBackend",
]
```

**To Reproduce**
I'm not quite sure about this part, but we're open to clarify if any statistic need to be taken from our pulp server.
We have a large number (~50k) of small rpm/file repositories (each contains ~10-15 packages/files), single user (admin) and 50k+ tasks running every day

**Expected behavior**
Django-guardian models are updated in way, what doesn't slow down task queue.

**Comment by dralley** [comment]
Related:

https://github.com/pulp/pulpcore/issues/2215
https://github.com/pulp/pulp_rpm/issues/2280

**Comment by AvoidMe** [comment]
We don't have memory issues in this one, just slow task-taking/saving and a lot of cpu consuming on Postgresql server

**Comment by dralley** [comment]
Ah, fair.

**Comment by mdellweg** [comment]
If you don't care about old tasks, it's probably worth using the tasks purge feature once in a while.

**Comment by mdellweg** [comment]
Can you try this:
https://django-guardian.readthedocs.io/en/stable/api/guardian.management.commands.html#std:command-clean_orphan_obj_perms

**Comment by AvoidMe** [comment]
Yes, seems like it helped, thanks
```
pulp=# select COUNT(*) from guardian_userobjectpermission;
 count 
-------
 39666
(1 row)
```
And the large query is executing under 200 ms.

**Comment by AvoidMe** [comment]
Yes, seems like it helped, thanks
```
pulp=# select COUNT(*) from guardian_userobjectpermission;
 count 
-------
 39666
(1 row)
```
And the large query is executing under 200 ms.

**Comment by mdellweg** [comment]
Sure this is not a proper solution...

**Comment by mdellweg** [comment]
Should we add this cleanup call to the orphan cleanup task?
