### ISSUE TITLE
Users who were authenticated by a remote web server need to exist in the database

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulpcore#2260]
**Users who do not exist in the database and were successfully authenticated by a remote web server, are not allowed to access any Pulp endpoint.**

In the documentation https://docs.pulpproject.org/pulpcore/authentication/webserver.html, we suggest modifying the AUTHENTICATION_BACKENDS and REST_FRAMEWORK['DEFAULT_AUTHENTICATION_CLASSES'] settings to enable remote authentication ("This will cause Pulp to accept any username for each request and not create a user in the database backend for them").

PulpRemoteUserAuthentication (https://github.com/pulp/pulpcore/blob/766a24960d00823a2573ab4aed142161b44265c9/pulpcore/app/authentication.py#L7) executes the following piece of code https://github.com/encode/django-rest-framework/blob/efc7c1d664e5909f5f1f4d07a7bb70daef1c396e/rest_framework/authentication.py#L230-L231 where https://github.com/django/django/blob/fe7dbef5867c577995f0fc849d8dfdb8f2e6bbfa/django/contrib/auth/backends.py#L184-L212 is called.

The method `user_can_authenticate` returns True. Overall, the method `authenticate` returns variable `user` that is set to `None` (https://github.com/django/django/blob/fe7dbef5867c577995f0fc849d8dfdb8f2e6bbfa/django/contrib/auth/backends.py#L195), which results in an HTTP 401 response.

User `admin` is created by default. Therefore, everything works correctly for him (Katello use-case).

**Comment by lubosmj** [comment]
I am not sure if this is a problem on our side. Based on the documentation, I would expect that once a user is authenticated by a remote web server (i.e., the `REMOTE_USER` header is set by nginx), he/she will be allowed to access Pulp endpoints regardless of his/her presence in the database.

**Comment by bmbouter** [comment]
I've gone back and forth with myself if this is an issue or not. I think the summary is that with Pulp getting authorization we need to consider how these authentication classes will or won't work with the admin-only use and with authorization provided by Pulp's RBAC and drf-access-policy. So to evaluate that can I ask you to provide a reproducer?

I think we need two things:
1) The settings you would put into `/etc/pulp/settings.py` to enable one or both of these backends
2) The nginx config diff that would forward the `REMOTE_USER` header to Pulp to have that authentication assume the user is authenticated.

@lubosmj can you provide these things and I could apply them to my dev env and take a look?

**Comment by lubosmj** [comment]
1. To mimic an authenticated user, I added this to the nginx config (`sudo vim /etc/nginx/nginx.conf`):
```diff
        location /pulp/api/v3/ {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Host $http_host;
            # we don't want nginx trying to do something clever with
            # redirects, we set the Host: header above already.
            proxy_redirect off;
            proxy_pass http://pulp-api;
+           proxy_set_header Remote_User admin;
        }
```

2. Append the following to the pulp settings file (`sudo vim /etc/pulp/settings`):
```diff
REMOTE_USER_ENVIRON_NAME = "HTTP_REMOTE_USER"
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "pulpcore.app.authentication.PulpNoCreateRemoteUserBackend",
    "guardian.backends.ObjectPermissionBackend",
    "pulpcore.backends.ObjectRolePermissionBackend",
]
REST_FRAMEWORK__DEFAULT_AUTHENTICATION_CLASSES = (
    "rest_framework.authentication.SessionAuthentication",
    "rest_framework.authentication.BasicAuthentication",
    "pulpcore.app.authentication.PulpRemoteUserAuthentication",
)
```

3. Rename file `.netrc` to `.netrc.old` to disallow `httpie` collecting credentials for Basic authentication automatically:
```
cd ~ && mv .netrc .netrc.old
```

4. Restart the pulp services and reload the nginx configuration file:
```
prestart && sudo nginx -s reload && sudo systemctl restart nginx.service
```

5. Try to access one pulp endpoint (working):
```
http https://pulp3-source-fedora35.localhost.example.com/pulp/api/v3/content/ -v
```

6. Now, change the nginx configuration to set the header to `test` instead of admin and access the same endpoint:
```
http https://pulp3-source-fedora35.localhost.example.com/pulp/api/v3/content/ -v
```
```
{
    "detail": "Authentication credentials were not provided."
}
```

**The issue was rather about whether it is an expected behaviour to not allow users, who do not have records in the database, to access pulp endpoints. So, I would at least suggest updating the docs to mention the existence of the backends
*guardian.backends.ObjectPermissionBackend*/*pulpcore.backends.ObjectRolePermissionBackend* and to mention the fact that users who are planned to be remotely authenticated *must* be in the database.**

**Comment by bmbouter** [comment]
I was able to reproduce this just as it described.

**Comment by bmbouter** [comment]
Actually now I get this error with this setup:

```
{
    "detail": "You do not have permission to perform this action."
}
```
