### ISSUE TITLE
As a user or developer, I can enable the memory recording of my tasks

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#2329]
This feature will be enabled by a setting named `RECORD_TASK_METRICS` which will default to `False`. When enabled, the directory `/var/lib/pulp/task_metrics/` will have files added to it.

The memory usage of the each task should be written periodically to the file `/var/lib/pulp/task_metrics/80/54bdac-1cfe-4c1b-91c2-1139fc316aeb.datum` where the UUID is split at the first two chars and the filename is the remaining portion of the UUID with `.datum`. on the end of it.

The memory should be recorded periodically.

**Comment by dralley** [comment]
Use `/var/tmp/pulp/` instead of  `/var/lib/pulp/`.  The RPM plugin already uses it for dumping diagnostics, and they get cleaned up automatically by the OS after a period of time (I believe the default is 1 month).

https://github.com/pulp/pulp_rpm/blob/main/pulp_rpm/app/depsolving.py#L849-L851

**Comment by bmbouter** [comment]
Great idea re the `/var/tmp/pulp/` dir.
