### ISSUE TITLE
Add more global access conditions for object parameters

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulpcore#2364]
We already have an access condition for the remote parameter when trying to perform a sync. Add more access conditions for other APIs that require a second object, like a repository or publication, upon distribution creation.

**Comment by mdellweg** [comment]
Can we add access conditions based on labels?
I am thinking that maybe a label "public" could make things visible/consumable for every authenticated user.

**Comment by gerrod3** [comment]
> Can we add access conditions based on labels? I am thinking that maybe a label "public" could make things visible/consumable for every authenticated user.

Not a bad idea, I think we would need to rethink (or at least accommodate) queryset scoping if we would want to add a feature like this. Thinking about it queryset scoping still isn't very intuitive for the user or how it interacts with the conditions...

**Comment by mdellweg** [comment]
Yes, configurable queryset scoping is still an unsolved problem.
