### ISSUE TITLE
Improve the dynaconf/config docs

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#2417]
One thing that's hard is that we don't clearly show example of how to set settings. We should add examples of common settings set.

**Comment by mdellweg** [comment]
That should cover config files (json, py, toml), environment variables (where to specify, how to name [double underscores] and what goes in [e.g. for complex settings]) and how to mix them, what takes precedence over the other.

**Comment by bmbouter** [comment]
I'll try to add some of that. I was hoping to contribute mostly examples of using those things to configure Pulp. I'm trying to avoid double-documenting dynaconf. It has a really big feature set. I do plan to link heavily into the very excellent https://www.dynaconf.com/ with the examples.
