### ISSUE TITLE
CONTENT_PATH_PREFIX don't working 

### ISSUE THREAD

**Issue by ekbfh** [pulp/pulpcore#2456]
**Version**
pulpcore-manager --version
3.2.12

Try at pulp:latest docker and 3.18 tags.

Main idea is to change base_url from `/pulp/content/` to `/repository/`, so i changed `CONTENT_PATH_PREFIX="/repository/"` in my settings.py and restart server with new settings.

Then i run `pulp [deb,rpm] distribution list` and see proper base_url, with `repository` path in it. 
But in browser i get 404 and `django.request:WARNING: Not Found: /repository/debian3/` in server logs.

Even when i trying to create full new repo,repote,publication and distro i get 404.

When i comment my var or change it to `pulp/content` everything is working fine even for repos, that was created few minutes ago.
What is the proper way of changing base_url?

**Comment by ekbfh** [comment]
My bad, i have found hardcorded location `pulp/content/ in nginx. I changed it and pulpcore is works fine

**Comment by mdellweg** [comment]
It is actually hard coded in the installer:
https://github.com/pulp/pulp_installer/blob/main/roles/pulp_webserver/templates/nginx.conf.j2#L75
If this is a desired feature we may want to move the issue there.

**Comment by ekbfh** [comment]
Yes, it'll be more logic when you have an opportunity to change this settings in pulp and can't in proxy. Or some text in documentation make a benefit
