### ISSUE TITLE
There's no way to tell what field an error comes from on the REST API

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulpcore#2504]
**Is your feature request related to a problem? Please describe.**

The error responses on the API are somewhat difficult to use. As an example, on the new `pulp/api/v3/roles/` api, if I try to create a new role with the following request body: `{"name":"foo","description":"","permissions":[]}` I get this error message: `{"description":["This field may not be blank."]}`. There's no indication which file may not be blank. Am I missing the description? Do I need to assign permissions for the object? It's not clear.

This is especially problematic when developing UI's for the Pulp API. There's nothing more frustrating than filling out a form and just getting a generic error back. User's need to be able to know where they've made a mistake and easily correct it.

**Describe the solution you'd like**

Errors thrown by the API should return an error message and the field that that the error message originates from when they are raised by a specific field.  

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mdellweg** [comment]
I do believe, "description" is the very field that tells you blank (as in `""`) is not allowed. Try `... "description": null ...` instead.

**Comment by ipanova** [comment]
```
$ http  https://pulp3-source-fedora34.fluffy.example.com/pulp/api/v3/distributions/container/container/ name="" base_path="" description=""
HTTP/1.1 400 Bad Request
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, POST, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 133
Content-Type: application/json
Correlation-ID: a58b2f458c734f8b8e8c5dd30abf4c66
Date: Mon, 11 Apr 2022 09:27:44 GMT
Referrer-Policy: same-origin
Server: nginx/1.20.1
Vary: Accept, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "base_path": [
        "This field may not be blank."
    ],
    "description": [
        "This field may not be blank."
    ],
    "name": [
        "This field may not be blank."
    ]
}

```

**Comment by mdellweg** [comment]
I came to the same conclusion. Closing the issue.

**Comment by newswangerd** [comment]
Hah, I feel stupid now. Thanks for clearing that up :)
