### ISSUE TITLE
Where do I apply the FORCE_IGNORE_MISSING_PACKAGE_INDICES=True global variable? 

### ISSUE THREAD

**Issue by saltyollpheist** [pulp/pulpcore#2563]
`No suitable Package index file found in 'dists/focal/main/binary-arm64'. If you are syncing from a partial mirror, try setting ignore_missing_package_indices to 'True' on your remote.`

I'm trying my best to figure out where exactly apply this variable - or preferably its global version `FORCE_IGNORE_MISSING_PACKAGE_INDICES=True` - in order to synchronize my Ubuntu 20.04.4 LTS repository with my Foreman+Katello setup. If someone - anyone - could please elaborate comprehensively where I need to put this variable and how to enable it properly, I would greatly appreciate it. 

Foreman+Katello is running on Rocky Linux 8.5 and is able to synchronize with its repository just fine. The only repository I'm having issue with is Ubuntu. 

`pulp --version` returns the following: 
`pulp3 command line interface, version 0.14.0`

**Comment by dralley** [comment]
I think this ought to be moved to the pulp_deb plugin, but I don't have the perms to move it to that repo.

**Comment by saltyollpheist** [comment]
Have reopened inquiry in [pulp/pulp_deb](https://github.com/pulp/pulp_deb/issues/481). Closing this post.
