### ISSUE TITLE
Downloader doesn't reset file on retries.

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulpcore#2576]
**Version**
3.14+

**Describe the bug**
When a network error occurs during download the retry logic doesn't reset the file.

**To Reproduce**
Reproducer test: https://github.com/pulp/pulp_file/pull/689

**Additional context**
https://issues.redhat.com/browse/AAH-1202

**Comment by fao89** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2033174
