### ISSUE TITLE
How to see an artifact filename?

### ISSUE THREAD

**Issue by lproj** [pulp/pulpcore#2594]
Hi,

I can successfully upload an artifact (e.g. .deb file) with 'pulp-cli' and delete it with 'http --form DELETE <href>".

Questions:
- How can I delete an artifact with 'pulp-cli'?
- How can I see the filename associated with an artifact to make sure I am deleting the right resource?

Thanks.

**Comment by gerrod3** [comment]
>     * How can I delete an artifact with 'pulp-cli'?

Currently the CLI doesn't support the delete endpoint on the artifact object. If you would like for this feature to be added you can file a feature request here: https://github.com/pulp/pulp-cli/issues/new/choose

>     * How can I see the filename associated with an artifact to make sure I am deleting the right resource?

Artifacts are just blobs of data and do not store any filenames. A user can upload multiple files with different names, but same content and only one artifact would be created. Each plugin has their own content  which are composed from artifacts (https://docs.pulpproject.org/pulp_deb/restapi.html#operation/content_deb_generic_contents_create) and have their own 'filename' (usually called relative-path). Use `pulp content list` to see all the content in Pulp and their associated artifact & filenames. If you haven't made any content from artifacts then you are going to have to use the artifact's sha256 checksum to know which one to delete.

**Comment by mdellweg** [comment]
If you just want to cleanup any unused content and artifacts (as in not associated with any repository version) you can do `pulp orphan cleanup --protection-time 0`.
