### ISSUE TITLE
Add test to verify the openAPI schema validates

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#2643]
Recently with [this change in 3.19](https://github.com/pulp/pulpcore/pull/2292) we now have a schema that validates with openAPI V2. I'd like to see a test that validates it.

**Comment by mdellweg** [comment]
I would think that we have openapi v3 in all cases.

**Comment by bmbouter** [comment]
Ah yes V3 it would have to be as that's the version of spec we now use. +1
