### ISSUE TITLE
pulpcore-content requires the database fields encryption key

### ISSUE THREAD

**Issue by mikedep333** [pulp/pulpcore#2694]
According to previous conversations, the pulpcore-content service shouldn't require the database fields encryption key.

However, pulpcore-content fails to start if it is not present. This error is seen in journald:
https://github.com/pulp/pulpcore/blob/80314fb1a402333042cd8bba1c02e935f608b321/pulpcore/app/settings.py#L398

**Comment by mdellweg** [comment]
I do not think this is correct. It _needs_ the key when generating (on-demand-)downloaders for remotes with configured credentials. It however will currently not attempt to _write_ to an encrypted field.

**Comment by mikedep333** [comment]
@mdellweg that makes perfect sense.

I guess I should close this issue then, or should we wait for someone else to confirm?

**Comment by mikedep333** [comment]
Closing in favor of adding the key in pulp_installer:
https://github.com/pulp/pulp_installer/issues/1069
https://github.com/pulp/pulp_installer/pull/1070
