### ISSUE TITLE
Group Role List - ordering by role name gives surprising order

### ISSUE THREAD

**Issue by himdel** [pulp/pulpcore#2703]
**Version**
```
galaxy_ng_version: "4.6.0dev"
pulp_ansible_version: "0.13.0"
pulp_container_version: "2.10.3"
pulp_core_version: "3.18.3"
```

**Describe the bug**
Ordering by role name in group role list gives surprising order.

**To Reproduce**
1. Have a group with multiple (rbac) roles assigned.
2. List those roles using `/pulp/api/v3/groups/45/roles/?ordering=role`

(I also tried `ordering=name` but that one gives the same order with or without `-` and it gives the same order for `ordering=whatever`, whereas `ordering=role` is sorting by something, just maybe not quite the right thing)

Actual results:

```
GET /pulp/api/v3/groups/45/roles/?ordering=role
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 8,
    "next": null,
    "previous": null,
    "results": [
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/b1572318-abce-486f-9668-a3f04a386b0a/",
            "pulp_created": "2022-05-09T21:10:04.578411Z",
            "role": "galaxy.admin_30227955-847a-40a1-891f-bd64ed17f116",
            "content_object": null
        },
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/cdd0c477-09c5-4fe1-b91f-141c19f369e6/",
            "pulp_created": "2022-05-09T16:36:09.374777Z",
            "role": "galaxy.admin_1f0f3338-9614-4e88-98f3-97f7e9af339d",
            "content_object": null
        },
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/0a6fcfbc-f8de-4016-b3f4-6edbd2385374/",
            "pulp_created": "2022-05-09T16:32:40.989792Z",
            "role": "galaxy.publisher",
            "content_object": null
        },
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/5f326769-679f-4ffe-b320-71d30b1353ba/",
            "pulp_created": "2022-05-09T21:10:04.580363Z",
            "role": "galaxy.admin_2c341dd0-7616-4429-a093-a081cddeb242",
            "content_object": null
        },
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/f3131b0e-3076-4b2f-a5fc-9aaeefbdf88c/",
            "pulp_created": "2022-05-09T21:10:04.578359Z",
            "role": "galaxy.admin_384d91ec-0ca1-46d9-9f2d-7001488a40f7",
            "content_object": null
        },
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/75d6b986-6adf-4c1f-a0fd-5d8448f26679/",
            "pulp_created": "2022-05-09T00:38:46.152970Z",
            "role": "galaxy.namespace_owner",
            "content_object": null
        },
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/d689b57b-4903-47c7-8a06-596046bd73c0/",
            "pulp_created": "2022-05-09T16:32:41.000804Z",
            "role": "galaxy.namespace_owner",
            "content_object": null
        },
        {
            "pulp_href": "/pulp/api/v3/groups/45/roles/0341f65c-ebe0-43cb-9b91-cc30db9b9990/",
            "pulp_created": "2022-05-03T20:51:56.804909Z",
            "role": "galaxy.delete-user_role",
            "content_object": null
        }
    ]
}
```

**Expected behavior**

I would expect all the `admin_*` roles together in any ordering by name .. and also `namespace*` does not go before `delete*`, and `publisher` goes after `admin`, etc. :) .. is it sorting by role id now?

**Comment by himdel** [comment]
`role__name` doesn't work either, neither does `role_name`, `role__role` or `role.name`

(I would try more similar things but I have no idea how pulp serialiizes these?)

**Comment by mdellweg** [comment]
My investigation in the ORM shows that

```
Cannot resolve keyword '§' into field. Choices are: content_object, content_type, content_type_id, group, group_id, group_roles, object_id, pulp_created, pulp_id, pulp_labels, pulp_last_updated, role, role_id, user_roles
```
we can basically on order on noninteresting fields, then again `role_id` does not work in the `ordering` querystring. I may need to dive further into the DRF `OrderingFilter` to understand that.

**Comment by himdel** [comment]
I think I can confirm that `ordering=role` causes it to filter by id...

`?ordering=role`: (uses `role_id ASC`)
`SELECT "core_grouprole"."pulp_id", "core_grouprole"."pulp_created", "core_grouprole"."pulp_last_updated", "core_grouprole"."group_id", "core_grouprole"."role_id", "core_grouprole"."content_type_id", "core_grouprole"."object_id" FROM "core_grouprole" WHERE "core_grouprole"."group_id" = 45 ORDER BY "core_grouprole"."role_id" ASC LIMIT 10`

`?ordering=-role`: (uses `role_id DESC`)
`SELECT "core_grouprole"."pulp_id", "core_grouprole"."pulp_created", "core_grouprole"."pulp_last_updated", "core_grouprole"."group_id", "core_grouprole"."role_id", "core_grouprole"."content_type_id", "core_grouprole"."object_id" FROM "core_grouprole" WHERE "core_grouprole"."group_id" = 45 ORDER BY "core_grouprole"."role_id" DESC LIMIT 10`

`?ordering=yyy`: (uses `pulp_created DESC`)
`SELECT "core_grouprole"."pulp_id", "core_grouprole"."pulp_created", "core_grouprole"."pulp_last_updated", "core_grouprole"."group_id", "core_grouprole"."role_id", "core_grouprole"."content_type_id", "core_grouprole"."object_id" FROM "core_grouprole" WHERE "core_grouprole"."group_id" = 45 ORDER BY "core_grouprole"."pulp_created" DESC LIMIT 10`

(unless that's just a pre-sort and django does more ordering in python, I don't know anything about django :))

**Comment by mdellweg** [comment]
All the ordering is done in the database (the only way to properly do pagination).

**Comment by himdel** [comment]
Reopening... with pulpcore 3.20dev:

http://localhost:8002/api/automation-hub/pulp/api/v3/groups/1/roles/?content_object=null&ordering=role&offset=0&limit=10
https://gist.github.com/himdel/32c69a7dab3f66a6ad601b49bd1cd87c

(and ordering=role__name is still treated as uknown)

**Comment by himdel** [comment]
Well.. except I can't actually reopen this, @mdellweg can you please? :)

**Comment by mdellweg** [comment]
Reopened by request.
But if i read this https://github.com/pulp/pulpcore/pull/2766/files#diff-808d829bc02e025b9af869c52edd0112faca44f98bd28b83e19e1d542bdccf38R370 correctly, the filter may be called "role" and then sort by "role__name" in the django ORM.
cc @himdel @newswangerd

**Comment by mdellweg** [comment]
I had a go on this and to me it seems to sort correctly when using `sort=role`. With `ordering=role` it still seems to produce a wierd order. This looks to me that we have managed to get two conflicting ordering filter implementations into Pulp.

**Comment by mdellweg** [comment]
Keep it open, i want to investigate this more. Especially if we really installed two sorting frameworks here.

**Comment by newswangerd** [comment]
oh interesting. Is this happening because I used `sort = filters.OrderingFilter(` instead of `ordering = filters.OrderingFilter(`?

**Comment by newswangerd** [comment]
@mdellweg I think it should be `order=` not `sort=`

**Comment by mdellweg** [comment]
Yes i figured this too by now...
For starters it is really only on the User/GroupRoles endpoints. But also we are mixing the `OrderingFilter` from DRF with the one from `django-filter`. The former is used throughout Pulp while the latter, i think, provides the lookup by related model fields.
There is something to sort out. Sadly my first attempt did not look like the latter is a drop-in replacement for the former.

**Comment by mdellweg** [comment]
My observation now:
In Pulp there is a `StableOrderingFilter` that is a subclass of DRF `OrderingFilter` attached by default to NamedModelViewset. However multiple view sets redefine their `filter_backends = (OrderingFilter, DjangoFilterBackend)` which is a bad idea.
With the DRF `OrderingFilter` (which is actually a `BaseFilterBackend` and not a `Filter`; very confusing), ordering across relations seems impossible. However, a DF(django-filters) `OrderingFilter` (which _is_ indeed a `Filter` as in "can be used as a field in a `FilterSet`") can be created in each and every `FilterSet` to allow for properly defined and complex sorting (more work, but full control). If we proceed that way, we should probably subclass it to a `StableOrderingFilter`. Probably the nicest solution would be to extend our `BaseFilterSet` to generate the `ordering=StableOrderingFilter(self._meta.ordering_fields)` from an attribute on it's meta-class. This too would stop using the DRF `OrderingFilter(Backend)` and incorporate ordering in the `FilterSet`.
