### ISSUE TITLE
issue for working on automation between BZ and github issues

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#2737]
**Version**
Please provide the versions of the pulpcore and plugin packages in use, and how they are installed.  If you are using Pulp via Katello, please provide the Katello version.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by dkliban** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2086694

**Comment by fao89** [comment]
testing...
