### ISSUE TITLE
Try to browse files via pulpcore_static -> e.g. landing page

### ISSUE THREAD

**Issue by mikch06** [pulp/pulpcore#2745]
**Version**
3.19.0

**Describe the bug**
I like to have a landing page or linklist on the pulp host.
I can't manage with multiple tries to browse a index/landing page trough document root /var/lib/pulp/pulpcore_static.

**To Reproduce**
Write an index.html file in /var/lib/pulp/pulpcore_static. Always got a 404.

**Expected behavior**
Like to browse html code with calling just the hostname without pulp/content

**Additional context**
Do i have to deactivate a code block in nginx config? Doument root is configured there but i have no chance.

**Comment by bmbouter** [comment]
Have you tried the browseable content app? I believe it's available at `/content/` on your pulp webserver. That endpoint on your reverse proxy is routing to the `pulpcore-content` app at the url `/content/` in case you wanted to request directly from that process instead. Try that, and let us know if it does or doesn't meet your needs.

**Comment by mikch06** [comment]
The document Root ist configured with "root /var/lib/pulp/pulpcore_static;" nginx.conf. But the directory is not browsable. 
I have not /pulp/content dir on the machine so far.

**Comment by bmbouter** [comment]
I'm going to close this for now, but please comment here if there is something we can do to improve things.

**Comment by mikch06** [comment]
Don't understand why it should be closed if it's not solved. but ok.

**Comment by mikch06** [comment]
As described in the initial post i simple try to run a landing page with some links to repos and side repos we have.
I run the current version:
      "component": "core",
      "version": "3.19.0"
yes -> pulp is installed!

I used the normal ansible installer, everything in unchanged installation. 

nginx.conf sais to run static pages with Document Root: "root /var/lib/pulp/pulpcore_static;" 

But this is not possible. 

That was my only question. 
I don't like to run oder use another django app, just put an index.html in a document root or so. 

Thx a lot.
