### ISSUE TITLE
Wrong ContentType header returned for some files via content app

### ISSUE THREAD

**Issue by dralley** [pulp/pulpcore#2811]
**Version**
All versions

**Describe the bug**
.xml.gz Files being served by the content app have a `ContentType` header of `text/xml` instead of `application/gzip`.

**To Reproduce**
Sync and publish any RPM repo, use HTTPie to request one of the files, observe the headers

**Expected behavior**
`ContentType` should be `application/gzip`, the type of the outer file rather than that of the decompressed contents.

**Additional context**
https://bugzilla.redhat.com/show_bug.cgi?id=2064092

**Comment by mdellweg** [comment]
Should the mimetype not be determined by the content being served? Or maybe the published artifact. Guessing the mimetype from the artifact is probably not a good idea. Also when on cloud storage, it means that we need to load the artifact into pulp for guessing. That is even worse.

**Comment by lubosmj** [comment]
There is also a good discussion about the similar problem of serving `.xml.gz` files in pulp2: https://pulp.plan.io/issues/1781#note-24. Adjacent comments reference the PR that resolves the issue.

Their workflow however does not work in our use case. In addition to that, I cannot simply add a new mime type to the existing database of types like this: `mimetypes.add_type("application/gzip", ".xml.gz")`. The type is still not correctly detected and returns `('text/xml', 'gzip')` all the time.

Loading artifacts from cloud storage is also a no-go for me.

**Comment by mdellweg** [comment]
Actually, it looks like we are guessing the mime-type just by means of the filename requested. So it is not a data from cloud issue. But still we are guessing where the content object could tell us the right answer.

**Comment by lubosmj** [comment]
> Should the mimetype not be determined by the content being served?

Currently, the type is determined by the extension of a file: https://github.com/pulp/pulpcore/blob/01557ca70f0863ec006977fb9bca6f8af8285dd6/pulpcore/content/handler.py#L337
