### ISSUE TITLE
As a user, I want to see if write only fields are set.

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulpcore#2825]
**Problem**

Some pulp APIs have write only fields for credentials and other sensitive information. These values (for obvious reasons) aren't displayed on the APIs. This presents two problems:

- Clients don't know which write only fields are available based on the api response.
- Clients don't know if write only fields are set, which makes it easy to accidentally reset them.

**Solution**

Galaxy NG has a "write_only_fields" serializer method that inspects the serializer for write only fields and returns them as a list on the api response:

Galaxy NG Implementation
- [Serializer](https://github.com/ansible/galaxy_ng/blob/78b83b1315bd611c7b36667a5c395ef86a522cfc/galaxy_ng/app/api/v3/serializers/sync.py#L62)
- [Helper function](https://github.com/ansible/galaxy_ng/blob/78b83b1315bd611c7b36667a5c395ef86a522cfc/galaxy_ng/app/api/utils.py#L97)

Sample Response
```json
{
	"name": "my_remote"
	"write_only_fields": [
		{
			"name": "token",
			"is_set": false
		},
		{
			"name": "password",
			"is_set": false
		}
	]
}
```

This could easily be ported over to pulp as a new serializer or serializer field that can be used by any serializer in pulp.

**Alternatives**
Add the field status to the field response. `"token": false` or `"token": true`. This doesn't work great because clients will think the value of `token` is false, and may not recognize the field is write only.

**Context**

Required for: https://issues.redhat.com/browse/AAH-756

**Comment by bmbouter** [comment]
+1 to the `write_only_fields` you have proposed here. I believe it should be implemented on the top-level machinery in pulpcore more-or-less paired with the same write-only-field redaction the serializers do today.

**Comment by newswangerd** [comment]
If this sounds good, I can have someone from our team contribute it to pulpcore.

**Comment by ipanova** [comment]
@newswangerd  to address this:
> Add the field status to the field response. "token": false or "token": true. This doesn't work great because clients will think the value of token is false, and may not recognize the field is write only.

You could maybe write something in a more explicit way:

```
{
	"name": "my_remote"
	"write_only_fields": [
		{
			"name": "token",
			"field_is_set": false
		},
		{
			"name": "password",
			"field_is_set": false
		}
	]
}
```

+1 on the proposal.
