### ISSUE TITLE
As a user I want to filter repositories by remote.

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulpcore#2864]
**Is your feature request related to a problem? Please describe.**
The galaxy ng UI needs to be able to fetch a list of repositories (or ideally distributions) that have remotes attached to them. The UI uses this to display repositories that are configured to be synced.

**Describe the solution you'd like**
The repository API has a remote field attached to it. I would like to be able to get a list of repositories that:
- Have a remote attached
- Have no remote attached
- Have a specific remote attached

Something like this would be nice on the distributions API as well. It would be great to see which distributions point to repos that have remotes, not remotes, or a specific remote.

**Describe alternatives you've considered**
We could use labels to track this stuff, but that would require enforcing specific sets of labels when creating repos. It would be better to just have a filter to handle this.

**Additional context**
Required for: https://issues.redhat.com/browse/AAH-756

**Comment by ipanova** [comment]
For the sake of trackability, @gerrod3  can you file a separate issue for distributions filter?
