### ISSUE TITLE
As a user, I want to know which distributions some content is in.

### ISSUE THREAD

**Issue by newswangerd** [pulp/pulpcore#2952]
**Is your feature request related to a problem? Please describe.**
There is currently no easy way for clients to find which distributions provide a specific piece of content.

**Describe the solution you'd like**
Add a` ?content_in=` filter to the distributions APIs that allow users to specify a content HREF and get a list of distributions that contain the selected content.

**Additional context**
This is needed for repository management in galaxy ng.

**Comment by mdellweg** [comment]
As this is a query to the Distribution, i'd name the filter like `with_content`, `has_content` or `serves_content` or something like that.

**Comment by lubosmj** [comment]
Should we close this issue then: https://github.com/pulp/pulpcore/issues/2865 ?

**Comment by mdellweg** [comment]
> Should we close this issue then: #2865 ?

No, the ask about querying repositories is a separate (and not as obvious) one. We may however cross the distribution off that other issues name.

**Comment by ipanova** [comment]
@lubosmj maybe in the future we will have a  usecase for this, and it will be a separate filter, but for now i'd focus getting done `distributions?with_content=pulp/href/123/.`
