### ISSUE TITLE
Facilitate removal of signing services in functional tests

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulpcore#2967]
Allowing testers to call a function for removing a signing service would be useful. Currently, we remove the signing service in the following manner: https://github.com/pulp/pulpcore/blob/6287ef36d2fc20ca316e1e889296fc55072ff477/pulpcore/tests/functional/gpg_ascii_armor_signing_service.py#L158-L168

Having a fixture `remove_signing_service(service_name, service_type)` accessible globally would suffice.

**Comment by mdellweg** [comment]
Actually, i think we should have a management command for admins too.

**Comment by mdellweg** [comment]
Also reading the original issue, i think we should not provide a `remove_signing_service` fixture per se, be call the management command in the cleanup code of the signing service fixture.
