### ISSUE TITLE
content app 404 message not always accurate

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#2977]
pulpcore 3.20.0 

Steps to reproduce:

Create an auto publishing repository.
Create a new repository version.
Create a distribution pointing to the repository.
Request a file from the distribution base_url that is not part of the repository version.

Notice that the 404 states 'Distribution is not pointing to a publication, repository or repository version.'

**Comment by mdellweg** [comment]
Is this reproducible with and without caching?
