### ISSUE TITLE
Can't purge tasks using pulp-cli

### ISSUE THREAD

**Issue by javihernandez** [pulp/pulpcore#2995]
**Version**
I'm using Pulp's official docker image (pulp/pulp:3.18), fetched a few days ago from docker hub.

**Describe the bug**
I was playing around with Pulp, had some tasks failed and tried purging them using pulp-cli as follows:
 ```pulp task purge --state failed```

I'm getting the following error:
```
Started background task /pulp/api/v3/tasks/9081599c-8730-4961-b108-c258ab7c4b77/
Error: Task /pulp/api/v3/tasks/9081599c-8730-4961-b108-c258ab7c4b77/ failed: 'Cannot use 'limit' or 'offset' with delete.'
```

**Expected behavior**
I expect it not to fail and purge the tasks

**Additional context**
I am not creating the issue against **pulp-cli** as I assume the problem is coming from [this line of code](https://github.com/pulp/pulpcore/blob/b575e1338e04978755a0231905950659aeea4ea9/pulpcore/app/tasks/purge.py#L74).

**Comment by mdellweg** [comment]
I believe we have test for this exact situation:
https://github.com/pulp/pulp-cli/blob/main/tests/scripts/pulpcore/test_task.sh#L59

Can you confirm your result?
Also can you attach the dump of that task too? (`pulp task show --href <...>`)

**Comment by javihernandez** [comment]
Hey, sorry for the late response. The other day, purging tasks worked great, but can't exactly tell what has changed. I have recreated my pulp container since then, but I'm still using the same image (_pulp/pulp:3.18_). Anyways, closing this as I can no longer reproduce the issue.
Thanks for your quick feedback!
