### ISSUE TITLE
Add another field to the `RepositoryVersion` model to store additional information.

### ISSUE THREAD

**Issue by hstct** [pulp/pulpcore#2998]
**Is your feature request related to a problem? Please describe.**

We are looking to implement an optimize sync feature in `pulp_deb`. In order to do that we want to store data in a `dict` format which contains information about the remote options used in the latest sync as well as `sha256` values for the repository files. These will be used to compare when trying to sync a repository again to see if something has changed and skip certain steps if it hasn't.

**Describe the solution you'd like**

Adding another field to `RepositoryVersion` model that can store a `.JSONField(default=dict)`. This way a repository can always look up the lastest version to get the previous data.

**Describe alternatives you've considered**

`pulp_rpm` uses their `Repository` model to save this data which works too. However there were concerns of the mutability of the data when stored this way.

Another solution would be adding a subclass of `RepositoryVersion` to `pulp_deb`. Since there is not any subclass of this model present in any plugin so far, this seems a bit overkill to just add one additional field.

**Additional context**

For context the PR for this feature in `pulp_deb`: https://github.com/pulp/pulp_deb/pull/570

**Comment by quba42** [comment]
Possible names for the new field:

1. `version_details`
2. `details`
3. `creation_details`

It is really an arbitrary JSON field, that could be used by plugin authors for almost anything, hence my first two suggestions are very generic. The use case we have in mind for `pulp_deb` is most accurately described by `creation_details`.
