### ISSUE TITLE
logging_cid in task response is an empty string

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3016]
Sometimes the logging_cid in the task response is an empty string:

```
        {
            "child_tasks": [],
            "created_resources": [],
            "error": null,
            "finished_at": "2022-07-25T21:32:09.435330Z",
            "logging_cid": "",
            "name": "pulpcore.app.tasks.telemetry.post_telemetry",
            "parent_task": null,
            "progress_reports": [],
            "pulp_created": "2022-07-25T21:32:09.383372Z",
            "pulp_href": "/pulp/api/v3/tasks/7f4c54d6-fcda-4006-9da1-3c6910a18171/",
            "reserved_resources_record": [],
            "started_at": "2022-07-25T21:32:09.419785Z",
            "state": "completed",
            "task_group": null,
            "worker": "/pulp/api/v3/workers/c609a0d5-45cc-4756-af3c-4b50cd7520b1/"
        }
```

Since logging_cid represents a uuid, I'd expect it to be null or a uuid. I don't think an empty string makes sense. It also makes our code that parses out uuid more complex because we have handle the possibility of empty strings.

**Comment by bmbouter** [comment]
In thinking this over, I expected every task to have a cid. There are tasks for example the telemetry posting that aren't initiated from an API call so there isn't a CID generated from django in that case, but maybe in that case the task should generate a CID?

This is an edge case scenario, but what if that task dispatched another task, shouldn't they both show the same CID?

**Comment by mdellweg** [comment]
> In thinking this over, I expected every task to have a cid. There are tasks for example the telemetry posting that aren't initiated from an API call so there isn't a CID generated from django in that case, but maybe in that case the task should generate a CID?
> 
> This is an edge case scenario, but what if that task dispatched another task, shouldn't they both show the same CID?

Exactly my line of thought. We should add enforcement for a cid in the proper uuid format for every task.

**Comment by ggainey** [comment]
+1 to "child tasks having the parent's cid", makes tracking who is doing what to whom in an async system WAY easier. Also, consistency is good - makes it easier on users' task-querying-code, if this field can *always* have a cid in it.

**Comment by bmbouter** [comment]
I think if [`get_guid()`](https://github.com/pulp/pulpcore/blob/0813377bb9919cce69498632535ae846d3f1f865/pulpcore/tasking/tasks.py#L90) returns None it should generate one and set it with set_uid() like [this](https://github.com/pulp/pulpcore/blob/f85381e36fdbd05426ec46d40035e787c39dd05d/pulpcore/tasking/pulpcore_worker.py#L441) does.
