### ISSUE TITLE
Modify the url of the remote keep the old packets of the old remote

### ISSUE THREAD

**Issue by orelops** [pulp/pulpcore#3040]
**Version**
```{
  "versions": [
    {
      "component": "core",
      "version": "3.20.0",
      "package": "pulpcore"
    },
    {
      "component": "rpm",
      "version": "3.17.7",
      "package": "pulp-rpm"
    },
    {
      "component": "file",
      "version": "1.10.3",
      "package": "pulp-file"
    },
    {
      "component": "container",
      "version": "2.13.0",
      "package": "pulp-container"
    },
    {
      "component": "ansible",
      "version": "0.14.0",
      "package": "pulp-ansible"
    }
  ],
```

**Describe the bug**
when i update a "remote" url, and then i sync, create a release and update the distro, i end up with the old packages from the old "remote"

**To Reproduce**
I will change this url `https://yum.theforeman.org/releases/3.1/**el7**/x86_64/` to `https://yum.theforeman.org/releases/3.1/**el8**/x86_64/`

Update the remote
`pulp rpm remote update --url https://yum.theforeman.org/releases/3.2/el8/x86_64/ --name foreman-3.2`

 Sync the repository using the remote 
`pulp rpm repository sync --name foreman-3.2`

Generate new publication
`pulp rpm publication create --repository "foreman-3.2"`

Update the distribution 
`pulp rpm distribution update --name foreman-3.2  --publication `"/pulp/api/v3/publications/rpm/rpm/83e56aaf-d41f-47f3-b7ea-ccd767zdddfa/"`

**Additional context**
I end up with the rpms el7 and el8
![Screenshot from 2022-08-05 15-13-26](https://user-images.githubusercontent.com/59478002/183085169-292b9fd2-ec1c-4cc8-b8ca-104a3a42f150.png)

I forgot something ?

**Comment by dralley** [comment]
>I forgot something ?

You need to perform the sync with `--mirror=False` set.

**Comment by orelops** [comment]
> > I forgot something ?
> 
> You need to perform the sync with `--mirror=False` set.

the same with : `pulp rpm repository sync --no-mirror --name "foreman-3.2" `

**Comment by orelops** [comment]
Has anyone encountered this problem before ?

**Comment by orelops** [comment]
```
Create a task to sync the repository using the remote.
Started background task /pulp/api/v3/tasks/e8896ecc-a758-4de8-9b83-25e2495fb333/
Done.
Set REPOVERSION_HREF from finished task.
Inspecting RepositoryVersion.
{
  "pulp_href": "/pulp/api/v3/repositories/rpm/rpm/940b039d-15f6-45a5-9d2b-b28855cc484f/versions/2/",
  "pulp_created": "2022-08-08T09:29:09.067767Z",
  "number": 2,
  "repository": "/pulp/api/v3/repositories/rpm/rpm/940b039d-15f6-45a5-9d2b-b28855cc484f/",
  "base_version": null,
  "content_summary": {
    "added": {
      "rpm.package": {
        "count": 740,
        "href": "/pulp/api/v3/content/rpm/packages/?repository_version_added=/pulp/api/v3/repositories/rpm/rpm/940b039d-15f6-45a5-9d2b-b28855cc484f/versions/2/"
      }
    },
    "removed": {},
    "present": {
      "rpm.package": {
        "count": 740,
        "href": "/pulp/api/v3/content/rpm/packages/?repository_version=/pulp/api/v3/repositories/rpm/rpm/940b039d-15f6-45a5-9d2b-b28855cc484f/versions/2/"
      }
    }
  }
}
```
old packages are not removed.

**Comment by dralley** [comment]
Apologies, I think I misread your original complaint.

If you *do not* want to keep the packages from previous syncs, use `--mirror`.

**Comment by orelops** [comment]
ok thank you @dralley
