### ISSUE TITLE
Add the ability to hide certificate guarded repositories from the listing present at `/pulp/content`

### ISSUE THREAD

**Issue by ehelms** [pulp/pulpcore#3061]
**Is your feature request related to a problem? Please describe.**
For repositories that are protected by client certificates, users desire a way for these to not appear on the listing page that is present when visiting `/pulp/content`. This behavior is how Pulp 2 worked and users have expressed a desire for it to return.

My understanding is that user's view these as protected, and more sensitive than repositories not guarded by client certificates and would prefer they do not appear as browsable in any way to users who do not have the proper client certificates to present to the server.

**Additional context**

There is a Satellite BZ that provides additional context and the originating request: https://bugzilla.redhat.com/show_bug.cgi?id=2088559

**Comment by mdellweg** [comment]
Can this be handled if that page was rendered as a (jinja2-) template?

**Comment by mdellweg** [comment]
Should users with the proper access (through the content guard) be able to see the paths again?

**Comment by ehelms** [comment]
The way it seems to work today is that all repositories within Pulp show up in a list when browsing to `/pulp/content/`, e.g. The repositories which are content guarded shouldn't appear in that list. That would be the simple blanket fix to the problem I think.

Users have expressed that if they present valid client certificates when visiting `/pulp/content/` they would see those content guarded repositories listed. I think this is a nice to have not a must have for almost all users.

Accessing an individual repository at it's fully qualified path is already protected and to my knowledge needs no additional work, e.g. if visit a content guarded repository I see:

```
403: [('PEM routines', 'get_name', 'no start line')]
```

(One could argue that should be a 404 rather than a 403.)

**Comment by dralley** [comment]
>The way it seems to work today is that all repositories within Pulp show up in a list when browsing to /pulp/content/, e.g. The repositories which are content guarded shouldn't appear in that list. That would be the simple blanket fix to the problem I think.

>Users have expressed that if they present valid client certificates when visiting /pulp/content/ they would see those content guarded repositories listed. I think this is a nice to have not a must have for almost all users.

I'm pretty certain we can do this in an hour or two in that case.

> Accessing an individual repository at it's fully qualified path is already protected and to my knowledge needs no additional work, e.g. if visit a content guarded repository I see:

Great news, glad there's no issue there

> (One could argue that should be a 404 rather than a 403.)

For obscuration purposes I presume?  (If you were spraying requests you could theoretically uncover which directories exist based on getting not-found or access-denied).

**Comment by ehelms** [comment]
> For obscuration purposes I presume? (If you were spraying requests you could theoretically uncover which protected directories exist based on getting not-found or access-denied).

Correct.

**Comment by dralley** [comment]
I believe so, yes.

**Comment by ipanova** [comment]
> > > For obscuration purposes I presume? (If you were spraying requests you could theoretically uncover which protected directories exist based on getting not-found or access-denied).
> > 
> > 
> > Correct.
> 
> I agree that this may be a valid concern, but i think that would be a separate issue. Should we have one filed?

I think we should distinguish between 404 and 403, in case users presents invalid client cert he should receive 403, imo.

**Comment by mdellweg** [comment]
> > > > For obscuration purposes I presume? (If you were spraying requests you could theoretically uncover which protected directories exist based on getting not-found or access-denied).
> > > 
> > > 
> > > Correct.
> > 
> > 
> > I agree that this may be a valid concern, but i think that would be a separate issue. Should we have one filed?
> 
> I think we should distinguish between 404 and 403, in case user presents invalid client cert he should receive 403, imo.

Isn't that a 401?
