### ISSUE TITLE
Download package from my browser gives me a hash as package name

### ISSUE THREAD

**Issue by orelops** [pulp/pulpcore#3124]
**Version**
 ```
"versions": [
    {
      "component": "core",
      "version": "3.20.0",
      "package": "pulpcore"
    },
    {
      "component": "rpm",
      "version": "3.17.7",
      "package": "pulp-rpm"
    },
    {
      "component": "file",
      "version": "1.10.3",
      "package": "pulp-file"
    },
    {
      "component": "container",
      "version": "2.13.0",
      "package": "pulp-container"
    },
    {
      "component": "ansible",
      "version": "0.14.0",
      "package": "pulp-ansible"
    }
  ],
```

**Describe the bug**
I therefore created a local repository to deposit the rpms built by our team, when I download a package from my browser (chrome or firefox) from this repository, the name of the downloaded file is a "hash" and not the name of the package, if I do the same test on a repository with a remote, I have no problem. Using S3 storage backend.

**To Reproduce**
1. create a repository without remote
2. upload a package to this repository
3. download package

![Screenshot from 2022-08-23 16-20-18](https://user-images.githubusercontent.com/59478002/186183155-b49064fa-cacd-4c34-acc7-b71c128c3485.png)

**Comment by mdellweg** [comment]
This may have been introduced by https://github.com/pulp/pulpcore/pull/2684

**Comment by newswangerd** [comment]
> This may have been introduced by #2684

The fix here looks wrong. When I inspect the request to s3 I get:

 `https://automation-hub-prd.s3.us-east-2.amazonaws.com/artifact/73/70b9aff0377c9943f2a8bd9b83e83e16d937aee126ad603e1a2990a902da18?response-content-disposition=attachment%3Bfilename=crowdstrike-falcon-3.2.21.tar.gz&response-content-type=application/x-tar&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=XXX&X-Amz-Date=20220919T141542Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=XXX`

And when I inspect the header in the response I'm seeing `Content-Disposition: attachment%3Bfilename=crowdstrike-falcon-3.2.21.tar.gz`, which looks invalid to me (none of the other headers return encoded characters)

It seems like you may have fixed the original issue by setting an invalid content disposition header.

@ipanova @bmbouter

**Comment by awcrosby** [comment]
Related AAH issue: https://issues.redhat.com/browse/AAH-1920
Possible related issue: https://github.com/pulp/pulpcore/issues/2964

**Comment by bmbouter** [comment]
@pulp/core this was identified by galaxy_ng as an important issue for their user base so it's getting the `prio-list` label.
