### ISSUE TITLE
Store sync options on the sync task

### ISSUE THREAD

**Issue by quba42** [pulp/pulpcore#3137]
**Is your feature request related to a problem? Please describe.**
This ticket follows on from a [discourse discussion](https://discourse.pulpproject.org/t/remote-fields-vs-sync-options/568), in particular, see [this comment](https://discourse.pulpproject.org/t/remote-fields-vs-sync-options/568/9?u=quba42).

In short: It can be very difficult to tell what sync options were originally sent with some sync API call after the fact.

This is especially true for sync options that are only set at the time of the sync API call, e.g.: pulp_rpm's [mirror, sync_policy, skip_types, and optimize](https://docs.pulpproject.org/pulp_rpm/restapi.html#tag/Repositories:-Rpm/operation/repositories_rpm_rpm_sync) fields. However, the problem also applies to remote options, since while the remote used is already saved on the sync task, there is no easy way of knowing how the remote was modified after it was used.

Example use case: Let's say I suspect that Katello may not have sent the right sync options to Pulp, but I have no way of knowing what Pulp received without adding extra debug logging and "catching it in the act".

**Describe the solution you'd like**
Some or all of the sync options (up for discussion if they are all needed), could be stored on the sync task for later reference. This could help with debugging, but also just to understand what that particular sync task was all about.

**Describe alternatives you've considered**
Sync task just strikes me as the obvious place, but I am not actually attached to this design. If somebody has a better idea I am all ears. So long as the information can be easily retrieved.

Full disclosure: In pulp_deb we now store roughly the information requested by this issue in the [`RepositoryVersion.info` field](https://github.com/pulp/pulpcore/blob/609ad733b75198463291f7c45598f0af29d37d11/pulpcore/app/models/repository.py#L614). However, that field is not exposed to users, and this was never intended as anything other than `optimize` sync feature plumbing.

**Comment by dkliban** [comment]
Closing in favor of https://github.com/pulp/pulpcore/issues/3155
