### ISSUE TITLE
Content app should (possibly) show index pages when the path is provided without a trailing slash

### ISSUE THREAD

**Issue by dralley** [pulp/pulpcore#3173]
***OR*** redirect from the non-trailing-slash URL to the trailing slash URL.

**Version**
Any

**Describe the bug**
It is completely valid in general to not yield an index page when the URL doesn't include a trailing slash, as the path looks like a file.  However, automatically redirecting to include this trailing slash is the default behavior of most webservers, including Pulp 2.

**To Reproduce**
Use curl / wget / http against a content app path that ought to display an HTML index page, receive 404

**Expected behavior**
Receive the index page or a redirect to the appropriate URL for the index page.

**Additional context**
https://bugzilla.redhat.com/show_bug.cgi?id=2104792

**Comment by ipanova** [comment]
This work was reverted, re-opening the issue  for better tracking

**Comment by lubosmj** [comment]
This depends on https://github.com/pulp/pulpcore/issues/3459

**Comment by dralley** [comment]
@dkliban This is a pretty meaty PR that, I believe, might require plugin author intervention - which is why it went into 3.40, the breaking change release.  Yes?

I'm guessing then that we don't necessarily want to backport this to 3.39?  It's currently targeted for 6.15.0 so it would be nice if we could... and we'd need to move it off if we can't... but it's also not that big a deal, we have no strong demand for this as far as I can tell.

**Comment by dkliban** [comment]
This cannot be backported to 3.39 because pulp_container requires a change that's only available in versions that are installable with pulpcore 3.40+

**Comment by dralley** [comment]
Ack, thanks.
