### ISSUE TITLE
Update requirements.txt with explicit upper and lower bounds (not use ~=)

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#3194]
Each of the dependencies needs to be examined to determine what the policy is for introducing breaking changes. This policy should be used to dictate the upper bound for that dependency. A comment with a link to the policy should be added to the requirements.txt. In cases where a policy is not declared, the most recent release should be used as the upper bound for the dependency.

**Comment by bmbouter** [comment]
The lower bound should be whatever the `~=` is today.

**Comment by bmbouter** [comment]
This was filed first, but the other I've already taken as assigned and has prio-list so I'm going to close this one. Thanks @ipanova for pointing this out.
