### ISSUE TITLE
Pulpcore and pulp_installer `cryptography` and `PyOpenSSL` version constraints result in unsolvable dependencies

### ISSUE THREAD

**Issue by m-bull** [pulp/pulpcore#3269]
**Version**
All `pulpcore` versions in combination with `pulp_certguard`.

**Describe the bug**
Installing or upgrading to any version of `pulpcore` using `pulp_installer` (or any method that uses `pip` to resolve dependencies) results in an unsolvable set of package dependencies.

pulp_certguard requires [PyOpenSSL <23.0](https://github.com/pulp/pulp-certguard/blob/67736d8f94a2c94f8e2a6baf92adcacc3654bd3a/requirements.txt#L1), for which `pip` selects PyOpenSSL 22.1.0, which includes https://github.com/pyca/pyopenssl/commit/f0ed288747a28a5785d7a62ef9e7afc699674625, which sets the minimum required `cryptography` version to 38.0.0. This constraint does not satisfy any of the tagged versions of `pulpcore`, for which the greatest acceptable `cryptography` version is 37.0.4.

I've opened this here rather than `pulp_certguard` because `pulpcore` has https://github.com/pulp/pulpcore/commit/eb0f4fe9bdd73429f60665a06bae45c427ad8882 on `main` allowing `cryptography==38.0.1`, which would solve the problem if it could be brought into a tagged/released version!

**To Reproduce**
Use various versions of `pulp_installer` with the `pulp_certguard` plugin enabled, and find an unsolvable pulp environment.

**Expected behavior**
Via `pip-compile`, `pulp_installer` is able to resolve dependencies of `pulpcore` and all enabled plugins.

**Comment by markgoddard** [comment]
@dkliban what was the result of the triage?
