### ISSUE TITLE
task filter reserved_resources_record does not work as expected

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulpcore#3280]
The task filter named `reserved_resources_record` specifies to be of type `array` in the openapi spec. But it only filters by the last entry in the list. Instead it should filter tasks that lock on all filtered resources.

Additionally, the filter is not aware of the `shared:` prefix.

**Comment by mdellweg** [comment]
Setting prio-list label because a related pulp-cli prio-list item depends on it.

**Comment by daviddavis** [comment]
We're currently using `reserved_resources_record`. I'm guessing we should switch to `reserved_resources` when 3.22 is released?

**Comment by mdellweg** [comment]
> We're currently using `reserved_resources_record`. I'm guessing we should switch to `reserved_resources` when 3.22 is released?

I think the old filter will still work the way it did before. But it's probably a good idea to switch for more consistent results.
