### ISSUE TITLE
Content app redirects break index.html files

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3309]
**Version**
3.21

**Describe the bug**
Pulp's content app by default uses redirects to serve content from object storage. The problem is that when serving index.html files (which pulp_python generates) some of the links in those files will not work correctly.

**To Reproduce**
1. Use object storage (eg S3)
2. Create a python distribution
3. Click on an index.html file
4. Observe that the browser url is now some S3 location and the relative links don't work.

**Expected behavior**
Pulp should serve index.html files instead of redirecting requests.

**Comment by daviddavis** [comment]
We are no longer experiencing this problem. I think setting `REDIRECT_TO_OBJECT_STORAGE` to false fixed it.

**Comment by mdellweg** [comment]
> We are no longer experiencing this problem. I think setting `REDIRECT_TO_OBJECT_STORAGE` to false fixed it.

That does not sound like a proper solution. This will stop _all_ content to be served by pulp-content streaming the bits from s6 to the user.

**Comment by daviddavis** [comment]
We had to disable `REDIRECT_TO_OBJECT_STORAGE` for other reasons. I think this could potentially not be an issue though as I'm not sure how pip handles this. Anyway, I leave it up to you all to decide to reopen this issue.
