### ISSUE TITLE
Tasks API should report a `finished_at` date/time for cancelled tasks

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#3319]
Cancelled tasks should have `finished_at` set at cancel time.
Ideally any attempt to set `finished_at` from something different than `None` in the database should be reported as a `RuntimeError`. (audit of all `Task.save()` and `Task.objects.update()` calls)

Original wording: Tasks API should return a `cancelled_at` date/time for tasks that were cancelled. The `finished_at` should be set to `null` when `cancelled_at` is not `null`.

**Comment by ipanova** [comment]
We have tasks in multiple final states - completed, failed, cancelled. Regardless on what state it is getting in the `finished_at` gets populated.
While your request makes sense, to make everything consistent we'd need to introduce besides `cancelled_at` also `failed_at`.

My preference would be keep things as they are  so we don't need to manage fields in addition. The combination of `state` and `finished_at` fields makes it pretty self explanatory of what happened to the task.

**Comment by mdellweg** [comment]
So i read that canceling would set the `finished_at` field as well.

**Comment by dralley** [comment]
I agree with Ina, I'm not sure I've seen justification for adding a new field just yet.  Is there a gap with `state: closed, finished_at: $date` doesn't cover?

**Comment by mdellweg** [comment]
The thing is that we seem to have canceled tasks with `finished_at: null` and `finished_at: <date>`. That should probably not be the case. `started_at` should then tell us whether the task was aborted or canceled before being started.

**Comment by ipanova** [comment]
> The thing is that we seem to have canceled tasks with `finished_at: null` and `finished_at: <date>`. That should probably not be the case. `started_at` should then tell us whether the task was aborted or canceled before being started.

I was not clear on this issue from the original report. It seems like we always set `finished_at` for canceled tasks https://github.com/pulp/pulpcore/blob/main/pulpcore/tasking/pulpcore_worker.py#L206 am i looking into wrong place?

@mdellweg For the sake of readability and preserving history - can you avoid editing original messages and rather add a comment?

**Comment by dralley** [comment]
>The thing is that we seem to have canceled tasks with finished_at: null and finished_at: <date>. That should probably not be the case. started_at should then tell us whether the task was aborted or canceled before being started.

Definitely agree that should not be the case, by what is the need for introducing a new field if we could just fix that bug?

**Comment by mdellweg** [comment]
> > The thing is that we seem to have canceled tasks with `finished_at: null` and `finished_at: <date>`. That should probably not be the case. `started_at` should then tell us whether the task was aborted or canceled before being started.
> 
> I was not clear on this issue from the original report. It seems like we always set `finished_at` for canceled tasks https://github.com/pulp/pulpcore/blob/main/pulpcore/tasking/pulpcore_worker.py#L206 am i looking into wrong place?
> 
> @mdellweg For the sake of readability and preserving history - can you avoid editing original messages and rather add a comment?

I recall that we edited the plan of an issue after the discussion took it into a different direction in the first message back on plan.io. And it made sense to me. So you didn't get confused reading the original request and then need to extract what actually to do from a lengthy discussion. For histroy purpose i kept the original text. Sorry if i confused you.
