### ISSUE TITLE
Dedicated (nested) api's to manipulate labels on objects

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulpcore#3332]
Currently you can only update the `pulp_labels` object as a whole. This can lead to all the common problems with concurrent updates.
Suggestion: Add a dedicated `{pulp_obj_href}/labels/` endpoint to allow crud operations on individual labels.

**Comment by ggainey** [comment]
discussion from openfloor:

ipanova
x9c4
: is the update call for labels is sync or async now?

x9c4@x9c4:x9c4.spdns.org
It's only accessible by updating the attached resource. And that may or may not be async.
also you need to set the dict of labels to be on an update call.

gerrod
so is this about updating an individual label? 

x9c4@x9c4:x9c4.spdns.org
yes.

gerrod
accept, I'm pretty sure we store the labels individually in the database so this is a serializer/endpoint change

ggainey
^change^addition :)
works4me

x9c4@x9c4:x9c4.spdns.org
This is only meant as an additional (safer) way to access the labels.
