### ISSUE TITLE
Bad filenames when using Azure Storage

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3342]
We're getting weird filenames (`dists_whatever_Release`) since upgrading to pulpcore 3.21.1. Looks like [this change](https://github.com/pulp/pulpcore/commit/0219fa407707c1fefa7cf44f756e8b9464cd0f5a) fixed the filenames so they are no longer SHA digests. However, `content_artifact.relative_path` [here](https://github.com/pulp/pulpcore/commit/0219fa407707c1fefa7cf44f756e8b9464cd0f5a#diff-453fdf3a6e81f92ff5391cf65f9c6154852133a656d82082021e3beaa887776fR813) includes the path so when you download a file, you somehow get the file's full path with slashes converted to underscores.

**Comment by ipanova** [comment]
to cover such case it appears we need to call:
```python
path = os.path.basename(content_artifact.relative_path)
content_disposition = f"attachment;filename={path}"`
```

**Comment by daviddavis** [comment]
Or maybe using pathlib:

```python
filename = Path(content_artifact.relative_path).name
content_disposition = f"attachment;filename={filename}"
```

**Comment by dralley** [comment]
Unfortunately, pathlib is slow, sometimes 20-50x slower than working with strings.  Since this is a hot path we should avoid it.

https://www.youtube.com/watch?v=tFrh9hKMS6Y

**Comment by dralley** [comment]
I closed https://github.com/pulp/pulpcore/issues/3346 as a duplicate
