### ISSUE TITLE
As a domain user, I can change my storage system credentials and Pulp will migrate my data

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#3358]
## Motivation

Assume the user is already a domain user. The user needs to migrate data from one storage backend to another. For example:

* I'm using local filesystem storage and I want to try the cloud cuz it's awesome.
* I'm using the AWS S3 and I want to try Azure Storage because our company decided to consolidate to Azure
* I'm using Azure and I want to switch to local filesystem because I realized [I'm overpaying](https://world.hey.com/dhh/why-we-re-leaving-the-cloud-654b47e0)

## Expectations

1. Pulp should copy the Artifacts from one storage backend to the other when a user changes their domain storage settings.
2. Pulp needs to remain online while this occurs.

## Technical planning

* It needs to happen asynchronously in the background as a task.

**Comment by ipanova** [comment]
Thanks for sharing that article, interesting read.
