### ISSUE TITLE
Version string on changes.html for the latest released docs is the version on main

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#3360]
The changes page[0] states the version is 3.22.0.dev in the top left corner of the page. 

The version is correct on the 3.21 version of the docs[1].

[0] https://docs.pulpproject.org/pulpcore/changes.html
[1] https://docs.pulpproject.org/pulpcore/en/3.21/changes.html

**Comment by pedro-psb** [comment]
Randomly got here.
