### ISSUE TITLE
AWS s3 integrating with pulp3

### ISSUE THREAD

**Issue by podman2020** [pulp/pulpcore#3361]
Version
We are using our own pulp-core components using containers based on this project.

Describe the bug
We are using assumedrolewithwebidentity and   AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN environment variables set, however pulp s3 connection is not working. we can import files to s3 bucket using simple boto3 .  any suggestions to configure aws s3 with web identitiy.

To Reproduce
connectivity to s3 bucket

Expected behavior
connect to s3 bucket and configure pulp directories

Additional context
It would be nice if we BOTO3 can read configuration files automatically if pod identity is enabled for AWS.

**Comment by gerrod3** [comment]
Hey @podman2020, if I'm understanding your question correctly you are trying to use Pulp with S3 and have Pulp use temporary security credentials (https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithWebIdentity.html) to access your S3? 

Currently Pulp uses django-storages `S3Boto3Storage` backend (https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html) to work with S3 and as such we only support the settings they support. Looking through their documentation I don't see any support for `AssumedRoleWithWebIdentity`. 

I'm not an S3 expert so there might be alternative ways to solve your problem (like having an external script copy the temp credentials to environment variables that `S3Boto3Storage` uses), but I would suggest filing a feature request against django-storages (https://github.com/jschneier/django-storages/issues) if you can't find a workaround.

**Comment by gerrod3** [comment]
@podman2020 Any updates on this issue?

**Comment by dkliban** [comment]
It's not clear what the bug is. Please feel free to re-open with more information.

**Comment by podman2020** [comment]
Sorry for the late reply. We were able to make it work by creating a profile in .aws/config with web identity token and export AWS_S3_SESSION_PROFILE
