### ISSUE TITLE
When upgrading without draining the task queue tasks can fail on version conflicts

### ISSUE THREAD

**Issue by mdellweg** [pulp/pulpcore#3368]
# Problem
When doing an upgrade, there may still be waiting tasks added by the api before the upgrade. Now running the workers with the upgraded codepaths, they may run into problems when a task function was removed / renamed or it's signature changed.
Even the semantics may have changed and lead to very subtle bugs.

# Solution
All worker code must be backwards compatible and properly handle tasks dispatched using an older codebase.

If we do not define a compatibility window here, workers need to establish compatibility forever.

**Comment by mdellweg** [comment]
We could also rather easily add a flag to the worker code to burst run (spin up one worker that will exit once the queue is empty).

**Comment by bmbouter** [comment]
That would be valuable anyway, but with zero-downtime upgrades it's possible the queue will never reach zero.
