### ISSUE TITLE
File System Exporter should have an option to generate listing files

### ISSUE THREAD

**Issue by parthaa** [pulp/pulpcore#3387]
**Is your feature request related to a problem? Please describe.**
When Katello uses the File System exporter it does not generate the listing files in CDN directory structure. Katello does not directly have access to the pulp's content directories. Due to this it is not able to easily generate `Listing` files. It relies right now on the hammer export command being run from the same machine as pulp.

**Describe the solution you'd like**
Pulp exporter should ideally have an option or a flag to generate `listing` files when fs exporter is run.

**Describe alternatives you've considered**
Couple of things to consider here 
- This is only relevant to YUM/KS repos
- This probably only useful for certain Yum repos. But a flag in the exporter would take care of that.

**Comment by dralley** [comment]
Why are listing files necessary?  What uses them?

**Comment by ggainey** [comment]
Listing files are usually the result of asking the serving webserver to auto-generate them.  There are also solutions/scripts out there to generate index.html files recursively. Generally speaking, server-admins want control over the L&F of index pages. I don't think it should be FilesystemExporter's job to do this - it belongs to the webserver admin of the site that ends up serving the content, not Pulp.

Recommend we not accept this RFE.

**Comment by dkliban** [comment]
This falls outside the responsibility of Pulp. A web server is better equipped to generate listing files.
