### ISSUE TITLE
Add pulp task wait helper command

### ISSUE THREAD

**Issue by bersace** [pulp/pulpcore#3390]
Hi,

Documentation of pulp rpm provde a bash implementation of `wait_until_task_finishes`. https://docs.pulpproject.org/pulp_rpm/workflows/scripting.html

I suggest to embed such feature in `pulp task wait`. AWS CLI has such feature.

What do you think of this ?
Regards

**Comment by mdellweg** [comment]
Isn't that `pulp task show --wait`?

**Comment by bersace** [comment]
@mdellweg Thanks, i missed that. Sorry for the noise.
