### ISSUE TITLE
Rename TELEMETRY setting to ANALYTICS

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#3417]
As was decided recently, the anonymous data gathered from Pulp installations is being called "Analytics" to avoid confusion with the [open telemetry working group](https://discourse.pulpproject.org/t/monitoring-telemetry-working-group/700) and the telemetry it will produce.

We've updated the term everywhere but in the pulpcore codebase. Here are some of the areas that need updating:
* The pulpcore code itself `git grep telemetry`, `git grep Telemetry`, `git grep TELEMETRY`.
* docs in [this section](https://github.com/pulp/pulpcore/blob/main/docs/components.rst#telemetry-collection)
* the TaskSchedule db entry
* the setting name itself.

I believe this should be listed as a breaking change although semver doesn't technically govern the settings themselves.

**Comment by daviddavis** [comment]
> I believe this should be listed as a breaking change although semver doesn't technically govern the settings themselves.

My team and I were quite surprised reading this comment. We had the impression that Pulp's semver policy did apply to its settings. It's a pain to have to check that settings could change with any release of Pulp.

What sort of policy does Pulp provide around settings? Obviously my hope is that Pulp would not remove/change settings between major releases but if that's not possible can you at least guarantee some number of Y releases?

**Comment by bmbouter** [comment]
My hope for Pulp as a project is to be very unsurprising for users, so your perspective here is helpful. I don't think we ever said one way or the other regarding settings, so maybe it's time we did. I'm reading a strong desire to never change a setting name and I can see why; it makes sense. I'll give it some thought. I'll comment on the PR also.

Thanks for joining the convo.

**Comment by mdellweg** [comment]
As per this setting (being of boolean nature), i think we agreed to introduce a new name, but keep the old name around as an alias.
We can now either make one of them higher priority than the other, or in this case, take the ORed value of both. It would be sufficient to switch of either one. Which one is less surprising?
