### ISSUE TITLE
Last item in api docs navigation pane not visible

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3426]
1. Go to https://docs.pulpproject.org/pulpcore/restapi.html
2. Scroll all the way down through the resources on the left
3. Observe that "Users: Roles" is the last item

It should be workers though. Here's a screenshot of what I see:

<img width="373" alt="image" src="https://user-images.githubusercontent.com/86290/203431035-62d1138b-1ff6-44ca-a254-3a4725b7e9b3.png">

But there is another item there for Workers that is obscured:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/86290/203431095-417830be-06a7-4631-90ea-f2c4b54b8da0.png">

**Comment by mdellweg** [comment]
Manually moving the div containing the "API docs by Redocly" banner out of the `scrollbar-container` div solved it for me. I fear this is a redocly bug.

https://github.com/Redocly/redoc/issues/2131
