### ISSUE TITLE
Pulp health checks without creating noise

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3433]
We're working on adding health/readiness checks for Pulp. I did some digging and found a few examples such as [this one](https://github.com/pulp/pulp-oci-images/blob/fd92edbf5785bb796b28e129dfcaeb116f59fc46/images/assets/readyz.py) in the pulp-oci-images project that checks the api and content app. However, it produces a lot of noise in the logs:

```
pulp-api  | ::ffff:127.0.0.1 - - [02/Dec/2022:19:48:45 +0000] "GET /pulp/api/v3/status/ HTTP/1.1" 200 880 "-" "python-requests/2.28.1"
pulp-api  | ::ffff:127.0.0.1 - - [02/Dec/2022:19:48:50 +0000] "GET /pulp/api/v3/status/ HTTP/1.1" 200 880 "-" "python-requests/2.28.1"
pulp-api  | ::ffff:127.0.0.1 - - [02/Dec/2022:19:48:55 +0000] "GET /pulp/api/v3/status/ HTTP/1.1" 200 880 "-" "python-requests/2.28.1"
pulp-api  | ::ffff:127.0.0.1 - - [02/Dec/2022:19:49:00 +0000] "GET /pulp/api/v3/status/ HTTP/1.1" 200 880 "-" "python-requests/2.28.1"
...
```

Another nice-to-have would be some docs with guidance on how to set up health/readiness checks for pulp.

**Comment by daviddavis** [comment]
FWIW, I think users are more interested in health checking the API and content app (more so than the workers since we can check worker health through the status endpoint).

**Comment by dralley** [comment]
@daviddavis Do you want specific routes silenced in the logs, or would you rather have the per-request logging silenced completely?  (or redirected to a different stream)

This is kind of similar to https://bugzilla.redhat.com/show_bug.cgi?id=1961508

**Comment by daviddavis** [comment]
I think I envisioned the former. This is sort of what I had in mind and what we're doing in our application:

https://github.com/pulp/pulpcore/pull/2845#issuecomment-1155625956

**Comment by dralley** [comment]
I think in practice we have many endpoints that could potentially be noisy, for example a lot of usage scenarios will continually refresh task statuses.

**Comment by ipanova** [comment]
should this ticket be closed in favor of https://github.com/pulp/pulpcore/issues/2844?

**Comment by daviddavis** [comment]
The only thing about #2844 is that it doesn't mention anything about not logging. If we can add that as part of the issue, then that should satisfy my need.

**Comment by daviddavis** [comment]
Also, it's not clear to me if #2844 also pertains to the content app.

**Comment by daviddavis** [comment]
I'm closing this out. We've worked around it and I can't think it's very useful to other users.
