### ISSUE TITLE
Observability MVP

### ISSUE THREAD

**Issue by dralley** [pulp/pulpcore#3445]
**Is your feature request related to a problem? Please describe.**

As a user I would like to be able to monitor the health and efficiency of my Pulp installation across a number of metrics, as it would provide insight into (and warning of) potential problems and misbehaviors, bottlenecks, etc.

**Describe the solution you'd like**

We would like to use the OpenTelemetry API / SDK for metrics collection.  For the initial implementation, we should do the following:

* Use the auto-instrumentation implementation provided for Django: https://opentelemetry-python.readthedocs.io/en/latest/examples/django/README.html
* Investigate the most suitable method of exporting those metrics
* Investigate what infrastructure will be necessary to make use of them
* Put a basic configuration in place in the development environment so that we can begin making use of them

Custom metrics aren't required, we just want to do the basic groundwork to enable them.

**Comment by dralley** [comment]
The content app would be a more useful place to start, but the auto-instrumentation for aiohttp on the server side doesn't exist yet 

https://github.com/open-telemetry/opentelemetry-python-contrib/pull/508
https://github.com/open-telemetry/opentelemetry-python-contrib/pull/942

**Comment by decko** [comment]
subscribing for pairing on this one. :grimacing:

**Comment by bmbouter** [comment]
I'm going to start on this, if someone else wants to take it over please do and let me know.

**Comment by dralley** [comment]
@bmbouter @decko Can this be closed now
