### ISSUE TITLE
Update pulpcore release instructions with info on pulp-oci-images

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#3514]
Pulpcore release instructions[0] need to have a section about releasing pulp-oci-images[1].

[0] https://github.com/pulp/pulpcore/blob/3.22/docs/release_process.rst 
[1] https://docs.pulpproject.org/pulp_oci_images/developer-instructions/

**Comment by ipanova** [comment]
please consider whether this is also the step that needs to be taken https://github.com/pulp/pulp-oci-images/pull/401

**Comment by ipanova** [comment]
steps 2 and 3 related to pulpcore release also would be beneficial to capture https://hackmd.io/gbTfH231RK-u1J2qjCcMLw?both
