### ISSUE TITLE
Task dispatch from django management command fails for blank guid

### ISSUE THREAD

**Issue by awcrosby** [pulp/pulpcore#3528]
**Version**
pulpcore==3.22.1, galaxy_ng==4.7.0dev

**Describe the bug**
When we dispatch a task from a django management command [1] we get the failure
`django.db.utils.IntegrityError: null value in column "logging_cid" violates not-null constraint`

With the recent removal of the default value for guid [2] pulpcore may want to generate a guid inside the task if one does not exist. 

Alternatively, galaxy_ng can resolve this inside our command by generating a guid before calling the task. If that is the preferred method, this issue can be closed.

[1] https://github.com/ansible/galaxy_ng/blob/113c51a5cb0bc57d8e9fc5fb3d79692f92c393b0/galaxy_ng/app/management/commands/set-repo-keyring.py#L80
[2] https://github.com/pulp/pulpcore/pull/3258/files#diff-b6921076eabe69f8f887286bbac04f5abb8c91b5e2e747b99ea932c5abf17135L179

**To Reproduce**
Dispatch a task from a django management command

**Expected behavior**
Dispatching a task from a django management command is possible without errors

**Comment by mdellweg** [comment]
Setting the guid is the preferred way. See an example in the link.

https://github.com/pulp/pulpcore/blob/d022295257529b21a8270a99b18e65a8726d5abf/pulpcore/tasking/tasks.py#L120

**Comment by awcrosby** [comment]
I see via https://github.com/pulp/pulpcore/issues/3016#issuecomment-1260768649 there is a desire to have the logging_cid generated if it does not exist  (maybe that only applies to `dispatch_scheduled_tasks`)?

But if #3016 is to enforce the caller to set the guid, we can certainly do that, just wanted to make sure it was fixed in the correct place.
