### ISSUE TITLE
The search in the pulpcore documentation is broken

### ISSUE THREAD

**Issue by quba42** [pulp/pulpcore#3569]
**Version**
Affects the released docs: https://docs.pulpproject.org/pulpcore/

**Describe the bug**
Searching using the search just has a spinning wheel forever.

errors in webconsole:
```
Uncaught ReferenceError: jQuery is not defined
Uncaught ReferenceError: $ is not defined
```

**Additional context**
Looks like this affects the pulp_rpm docs as well. pulp_deb docs were still unaffected last I checked but I am not sure how recently we released a new version.

**Comment by dkliban** [comment]
Looks like we are affected by https://github.com/readthedocs/sphinx_rtd_theme/issues/1434

**Comment by dkliban** [comment]
I am going to try installing sphinxcontrib-jquery==3.0.0 locally to see if it fixes the issue.

**Comment by dkliban** [comment]
That did not fix the problem. Installing sphinx-rtd-theme==1.1.1 did fix the problem. I am going to pin the sphinx-rtd-them to < 1.2.0

**Comment by benjaoming** [comment]
Hi @dkliban - a new sphinxcontrib-jquery has been released (4.1), so you should be able to use the latest auto-resolved sphinxcontrib-jquery that comes with `sphinx-rtd-theme==1.2.0`.

**Comment by gherceg** [comment]
Hi @benjaoming, I tried upgrading `sphinxcontrib-jquery` to v4.1 with `sphinx-rtd-theme` pinned to v1.2 and `sphinx` pinned to v6.1.3, but still experienced the `ReferenceError: jQuery is not defined` when using the search bar. Let me know if I can provide any more helpful information.

**Comment by ipanova** [comment]
@benjaoming seems like neither pinning spnhinxcontrib-query and sphinx-rtd-theme helps.

**Comment by benjaoming** [comment]
Edit: That's what I think you should do to get things working with the latest version. But pinning things is a fine approach, there's no harm in being a few minor versions behind :+1:

**Comment by lubosmj** [comment]
@benjaoming, thanks, the changes related to the config file helped to resolve the issue. 🥳 

https://github.com/pulp/pulpcore/pull/3668
