### ISSUE TITLE
Add 'distribution_extra_fields' to the Replicator interface

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#3649]
The Replicator provide 'remote_extra_fields' and 'repository_extra_fields' that plugin writers can use to customize remote and repository creation during the replication task. The same should be available for Distributions.

**Comment by gerrod3** [comment]
Has this been completed with the addition of `distribution_data`? https://github.com/pulp/pulpcore/commit/a1dd579e5aa831c1dd69b3dc028c6e9108bab06e Should this be renamed to `distribution_extra_fields`, or just leave it as is?

**Comment by gerrod3** [comment]
Can you explain more how we would move this to pulp-glue?

**Comment by mdellweg** [comment]
I don't remember what i was thinking. Also the idempotence will not help here because we don't use glue to create the stuff locally, but only to inquire it on the remote end.

**Comment by gerrod3** [comment]
Do you think we should close this issue since it has already been kind of completed?

**Comment by mdellweg** [comment]
Consistency in naming things would be nice.
