### ISSUE TITLE
Package timestamp on the content dir listing page should reflect the time when it was added to the repo

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3653]
In pulpcore 3.22, a timestamp was added to the content directory listing page. The timestamp uses the content artifact created date. However, it should use the time when the package was added to the repo (the RepositoryContent created time) as this is what users would expect especially in cases where someone else might have uploaded the packages.

**Comment by daviddavis** [comment]
Our use case: users promote packages from one repo to the next and they want to know at which time the package was "published" (or added to a repo).

**Comment by dkliban** [comment]
I see this as a bug. The pages displayed by pulpcore-content are designed for users of the repository to browse the content of the repository. The date a user expects to see is that of when the package became available in that repository.
