### ISSUE TITLE
Task listing is extremely unoptimized.

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulpcore#3711]
**Version**
pulpcore <=3.23

**Describe the bug**
Listing out tasks causes 100s-1000s of queries to the database with a small set of tasks ~100. Many can be fixed by adding `prefetch_related` for `"child_tasks", "progress_reports"`. `created_resources` will need special optimization to prevent each resource from being their own query.

**Comment by decko** [comment]
![image](https://user-images.githubusercontent.com/20204/230376379-1085e4ae-8c70-4cd1-b144-dfd1ae8e479c.png)
Can this image be of any help?
