### ISSUE TITLE
As a user, I can filter repos if they currently contain a particular piece of content

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulpcore#3732]
We'd like a way to filter repos if they currently contain a piece of content (ie if their latest repo version has a particular package, etc). 

This is somewhat achievable today but it's not easy (especially when you are dealing with paginated results):
1. Filter repo versions using the repo version content filter
2. Find which versions are the latest versions
3. Look up the repo for each latest version

What would be ideal would be a content filter on the generic repo endpoint sort of like [the content filter on the repo version endpoint](https://github.com/pulp/pulpcore/blob/50bdd1ba0d2ce7ae4d6eef15a2dd7c569d49c03a/pulpcore/app/viewsets/repository.py#L116). This would filter the repos if they have a piece of content in their latest version.

**Comment by lubosmj** [comment]
Is this a duplicate of https://github.com/pulp/pulpcore/issues/2865?

**Comment by daviddavis** [comment]
I'm reopening this issue since #2865 is about repos AND distributions. I have a PR and I don't want it to close #2865 since it only handles the former resource.

**Comment by daviddavis** [comment]
Nevermind, I see that https://github.com/pulp/pulpcore/issues/2952 implemented the distribution filter.
