### ISSUE TITLE
Pulp unable to pick up correct/available checksum.

### ISSUE THREAD

**Issue by Raptus1** [pulp/pulpcore#3739]
**Version**
3.22.2 Using Pulp Operator

**Describe the bug**
A clear and concise description of what the bug is:
"Task failed to complete. (failed; On-demand content located at the url https://packagecloud.io/netdata/netdata/el/9/x86_64/netdata-plugin-cups-1.35.0-1.el9.x86_64.rpm contains forbidden checksum type, thus cannot be synced. You can allow checksum type with 'ALLOWED_CONTENT_CHECKSUMS' setting.)",

There is several checksums available on PackageCloud: MD5, SHA1, SHA256, SHA512, where Pulp default allowed is at least one of them.

Seems like it fails on MD5 as this is outdated, Then it fails over to try SHA1 which is also outdated and then does not try any more and just fails the task.

**To Reproduce**
Use PackageCloud as repo and sync using Pulp Squeezer ansible module.

**Expected behavior**
A clear and concise description of what you expected to happen:

Sync to complete with no issues

**Comment by dralley** [comment]
>There is several checksums available on PackageCloud: MD5, SHA1, SHA256, SHA512, where Pulp default allowed is at least one of them.

It may provide several options but if you are talking about RPM repositories, only one of them is actually being used at a time.  Is the one configured to be used one which is present in the ALLOWED_CONTENT_CHECKSUMS setting?

**Comment by dralley** [comment]
@Raptus1 Could you elaborate?
