### ISSUE TITLE
'null value in column "pulp_labels" of relation "core_distribution"

### ISSUE THREAD

**Issue by acteru** [pulp/pulpcore#3753]
Getting this error when trying to distribute a rpm repository. Not sure if this is really a bug or just a database migration was gone wrong in the past. 

**Version**
 ` "versions": [
    {
      "component": "core",
      "version": "3.22.0",
      "package": "pulpcore"
    },
    {
      "component": "rpm",
      "version": "3.18.9",
      "package": "pulp-rpm"
    },
    {
      "component": "python",
      "version": "3.8.0",
      "package": "pulp-python"
    },
    {
      "component": "deb",
      "version": "2.20.1",
      "package": "pulp_deb"
    },
    {
      "component": "container",
      "version": "2.14.3",
      "package": "pulp-container"
    },
    {
      "component": "file",
      "version": "1.11.2",
      "package": "pulp-file"
    },
    {
      "component": "certguard",
      "version": "1.5.5",
      "package": "pulp-certguard"
    },
    {
      "component": "ansible",
      "version": "0.16.0",
      "package": "pulp-ansible"
    },
    {
      "component": "maven",
      "version": "0.3.3",
      "package": "pulp-maven"
    }
  ],`

**Describe the bug**

Adding a new Repository and trying to distribute after sync.

```
pulp rpm publication create --repository Rocky9-crb
Started background task /pulp/api/v3/tasks/96325faa-4a8f-45eb-a3e6-75198257357b/
.............................Done.
{
  "pulp_href": "/pulp/api/v3/publications/rpm/rpm/1141a32e-e9ab-4422-9d30-a439b5758716/",
  "pulp_created": "2023-04-20T11:38:48.096703Z",
  "repository_version": "/pulp/api/v3/repositories/rpm/rpm/aae62fd6-8729-40a8-8f43-6e4b00d57f26/versions/2/",
  "repository": "/pulp/api/v3/repositories/rpm/rpm/aae62fd6-8729-40a8-8f43-6e4b00d57f26/",
  "metadata_checksum_type": "sha256",
  "package_checksum_type": "sha256",
  "gpgcheck": 0,
  "repo_gpgcheck": 0,
  "sqlite_metadata": false
}

pulp rpm distribution create --name Rocky9-crb_distribution --base-path Rocky_9_crb --publication /pulp/api/v3/publications/rpm/rpm/1141a32e-e9ab-4422-9d30-a439b5758716/
Started background task /pulp/api/v3/tasks/0b048fbe-5391-4964-916f-dae0aa30e7c9/
.Error: Task /pulp/api/v3/tasks/0b048fbe-5391-4964-916f-dae0aa30e7c9/ failed: 'null value in column "pulp_labels" of relation "core_distribution" violates not-null constraint
DETAIL:  Failing row contains (5a68ce19-e00e-4d9c-a55a-f6de0c86959d, 2023-04-20 11:46:01.167616+00, 2023-04-20 11:46:01.167635+00, rpm.rpm, Rocky9-crb_distribution, Rocky_9_crb, null, 1141a32e-e9ab-4422-9d30-a439b5758716, null, null, null, null).
```

**Expected behavior**

The distribution can be created without failing any requirements for pulp_labels.

**Comment by lubosmj** [comment]
Is this a duplicate of https://github.com/pulp/pulpcore/issues/3495?

**Comment by acteru** [comment]
Hm, yes, looks like it - will close this issue here
