### ISSUE TITLE
Remove references to pulp_installer as supported installation method

### ISSUE THREAD

**Issue by ipanova** [pulp/pulpcore#3834]
[ipanova@puffy pulpcore]$ git grep pulp_installer | wc -l
24

**Comment by quba42** [comment]
:heart:

**Comment by quba42** [comment]
Ideally also consider the following:

- [ ] Ensure there is a big fat DEPRECATED box here: https://github.com/pulp/pulp_installer#readme
- [ ] Ensure there is a big fat DEPRECATED box here: https://docs.pulpproject.org/pulp_installer/ (Requires one more doc release)
- [ ] Read only the pulp_installer repo?

**Comment by ipanova** [comment]
@quba42 thanks, there is a corresponding issue opened for that https://github.com/pulp/pulp_installer/issues/1478
