### ISSUE TITLE
Remove references to systemd altogether

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#3912]
systemd is no longer helpful in documenting for our users, here's why:

1) Users running standalone containers can just use podman or docker to start/stop the container. They can also use `podman generate systemd --new --files --name pulp` to have those tools generate systemd containers

2) Users running docker/podman compose has the compose tooling handle the start/stop/restart states of the containers

3) Users runnning k8s, openshift, or the operator don't use systemd

4) Users doing manual pip installation may have any number of ways to manage their services start/stop/restart. It's really not a Pulp specific thing.

**Comment by mikedep333** [comment]
Hey, as we discussed about a month ago, instead of remove the systemd templated service files, let's convert them into non-templated service files. And embed them in the docs.

A lot of users want them, and a sysadmin I would too.

**Comment by bmbouter** [comment]
That doesn't make sense to me, but I'm ok to not remove them if you want to keep them. We can close this for now and I'll close the associated PR.
