### ISSUE TITLE
As a user I can gracefully shut down a pulpcore-worker

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#3940]
A user should be able to stop a `pulpcore-worker` in such a way that allows the worker's current task to run to completion.

**Comment by mdellweg** [comment]
Currently, when you sigint a worker, it will wait for a few heartbeats before killing the current task. This is only working for short tasks obviously, but I leave it here for context.

**Comment by mdellweg** [comment]
Is this about sending SIGUSR1 to the worker, or do we need to make this available from the api?

**Comment by ipanova** [comment]
How useful will this be with a long running task like sync? Is there an expected max time within which the worker would supposedly gracefully shutdown?

**Comment by mdellweg** [comment]
You can still kill the worker in the usual way if the graceful way didn't get you anywhere.

**Comment by ipanova** [comment]
> You can still kill the worker in the usual way if the graceful way didn't get you anywhere.

that's where i was getting at with the question of expected max time ;)

**Comment by decko** [comment]
> > You can still kill the worker in the usual way if the graceful way didn't get you anywhere.
> 
> that's where i was getting at with the question of timeout ;)

And this answer is also helpful when we need to terminate the pods of the `pulp-operator` for any needed reason.
