### ISSUE TITLE
BaseDownloader.fetch passes coroutine to asyncio.wait which is forbidden in python 3.11

### ISSUE THREAD

**Issue by EamonTracey** [pulp/pulpcore#4107]
Python 3.8 deprecated passing coroutines to `asyncio.wait` and Python 3.11 will now [raise an error](https://github.com/python/cpython/blob/a6313d78f21f79ca64dedd38e637509dc530a1b6/Lib/asyncio/tasks.py#L414C13-L414C13). This causes the BaseDownloader.fetch call to fail on Python 3.11 https://github.com/pulp/pulpcore/blob/9dbcc8810f97f53297a933df2e1b74cdc324a8ea/pulpcore/download/base.py#L185 .

Python provides the solution in the error message:  "Passing coroutines is forbidden, use tasks explicitly."

I believe this can be fixed by explicitly converting the coroutine to a task using asyncio's `create_task`

**Comment by mdellweg** [comment]
Honestly why is it wrapped inside `asyncio.wait` anyway?
Also please read the python docs carefully about when things got added. There was confusion about the availability of create_task vs. ensure_future depending on the python version before.
We need to maintain at least python 3.8 compatibility.
