### ISSUE TITLE
Repair API should be tolerant of any failure during the repair process

### ISSUE THREAD

**Issue by ipanova** [pulp/pulpcore#4111]
**Version**
main and older

**Describe the bug**
We have made repair api tolerant to a 404 error but that is not the only error that someone can receive. 

If remote is associated with a proxy and that proxy is limiting connections or misconfigured someway, Then TimeoutException would be a common thing to occur as well. 
If Firewall is not properly configured that may even result in "Connection Reset".

No matter what the failure is, The Repair API, should not halt but continue processing rest of the units that it has identified as corrupted or missing.

**To Reproduce**

**Expected behavior**

**Additional context**
https://bugzilla.redhat.com/show_bug.cgi?id=2173692#c13
https://github.com/pulp/pulpcore/issues/3611 cope with 404

**Comment by vijaysawant** [comment]
I would request you to look at 6.13.3 Failed QA BZ's traceback which is here https://bugzilla.redhat.com/show_bug.cgi?id=2218980#c2 and we need to consider "DigestValidationError" error as well in the fix of upstream issue request https://github.com/pulp/pulpcore/issues/4111, as this checksum verification is another issue CU are facing.
