### ISSUE TITLE
Allow S3 compatible storage

### ISSUE THREAD

**Issue by jbertozzi** [pulp/pulpcore#4163]
**Is your feature request related to a problem? Please describe.**
Only S3 storage from AWS seems to be supported, it would be nice to allow S3 compatible storage (ie: MinIO).

**Describe the solution you'd like**
Add a few variables to support local endpoint the same manner terraform backend s3 storage do (at least S3_ENDPOINT and probably S3_FORCE_STYLE_PATH):
https://developer.hashicorp.com/terraform/language/settings/backends/s3#s3-state-storage

**Comment by mdellweg** [comment]
Our ci uses minio to test the s3 backend. I'm sure this is fully supported.
Detail documentation may be found on the django-storages side.

**Comment by dkliban** [comment]
https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html#amazon-s3 

You can set AWS_S3_ENDPOINT_URL when configuring DEFAULT_FILE_STORAGE.
