### ISSUE TITLE
Export artifact-dedup optimizations break pulp_rpm export.

### ISSUE THREAD

**Issue by ggainey** [pulp/pulpcore#4210]
**Version**
main, 18, 21, 22, 23, 28, 29

**Describe the bug**
After the changes for #4159 were released, pulp_rpm nightly tests started failing. This turns out to be the result of a subtle bug in the optimizations introduced for that fix.

This has to be fixed and released ASAP to all versions #4159 was releasxed into.

**To Reproduce**
* Run https://github.com/pulp/pulp_rpm/blob/main/pulp_rpm/tests/functional/api/test_pulpimport.py#L287

**Comment by ggainey** [comment]
The specific test-failure that brought this to light was : 
```
pulp [1aa88cb7-e5d6-4cb1-8890-f64b74fe80bc]: pulpcore.app.tasks.importer:ERROR: FATAL import-failure importing ./tmp5atvoa1n/repository-89e18c83-bc2b-4632-8bfb-45517d1e0504_1/pulpcore.app.modelresource.ContentArtifactResource.json
pulp [1aa88cb7-e5d6-4cb1-8890-f64b74fe80bc]: pulpcore.tasking.tasks:INFO: Task 0189a2e6-b8c5-72d5-b5e9-485bc9970581 failed (Artifact matching query does not exist.)
```

Artifacts needed by the ks-tree mentioned in the test were not exported correctly, and were therefore not being found at import-time.

**Comment by dralley** [comment]
Do you know why the queryset approach was interfering?

**Comment by ggainey** [comment]
> Do you know why the queryset approach was interfering?

I do not. It may be some interaction with the sub-repos of distribution-trees and multiple-repos, that's the only sequence that fails. 

The current released behavior breaks the main-path workflow, and digging further into "why" was a lower priority than "make it work first". Replacing the approach with a set() means the current state of the attached PR is still **significantly** better than it has been for the past three years.

Maybe we want to do some more investigation "eventually" - but "stopping the bleeding Right Now" is today's priority.
