### ISSUE TITLE
Make orphan clean up more torelant to the failures during content removal

### ISSUE THREAD

**Issue by ipanova** [pulp/pulpcore#4316]
**Version**
all

**Describe the bug**
Orphan clean up can fails when it encounters content that was identified as orphan but because of some other tasks that might be running in parallel, e.g. sync it might be adding the content to the repo. In that case task will fail on the very first occurrence of such content. We should make orphan cleanup content more tolerant to such cases.

Some plugins declare content dependency where a content( orphan) cascade deletes another content(non-orphan).
The question is how orphan cleanup should handle such case when it does not have specific plugin knowledge.

The suggestion to handle these both cases is to by-pass problematic content that cannot be removed, log it and proceed. 

**To Reproduce**

**Expected behavior**

**Additional context**
Add any other context about the problem here.  Please provide links to any previous discussions via Discourse or Bugzilla.

**Comment by ipanova** [comment]
Copied from other issue discussion:

dralley:
About the PR, it seems the discussion is along the lines of:

-     don't merge it, let the orphan cleanup fail but figure out how to communicate to the user that they should use a script / tool we provide to repair the situation

-     merge it, bypass "problematic" content units, just print it in the logs, and maybe also provide that script

I think we should see what we can do in terms of repair before we necessarily make a decision either way in terms of the PR.

ipanova:
idk about the repair part in both bullet points of yours, the script should be plugin self aware otherwise how it should know what to do with e.g. debian Package, or PackageReleaseComponent? Blindly removing FK does not seem like a good idea.

more discussion here https://github.com/pulp/pulpcore/issues/4209#issuecomment-1686820677

**Comment by dralley** [comment]
Agreed that it would need to be plugin-aware and live in the debian plugin, which would make it challenging to notify the user about from Pulpcore.
