### ISSUE TITLE
Need a way to force *async* execution of a DELETE task

### ISSUE THREAD

**Issue by sskracic** [pulp/pulpcore#4372]
**Version**
pulpcore-3.28.10
pulp-rpm-3.22.3

**Describe the bug**
Deleting a handful of repositories with large RPM content now takes hours instead of minutes.

**To Reproduce**
1. sync RHEL 8 baseos and appstream repos from CDN
2. try to delete them
3. since all delete calls are now synchronous, the deletion is performed in a singlethreaded fashion, instead of being distributed across available pulp workers (8 or 16, depending on the installation).  It now takes hours instead of couple of minutes.  In addition, during this time the API gunicorn worker is completely blocked and is unavailable to process other requests.
**Expected behavior**
I would like an API addition (eg. a flag ?async=true) that would force my DELETE /repositories/rpm/rpm/ call to be asynchronous and distributed to either an available worker or, failing that, put in the pending queue.
**Additional context**
Performance of a repository deletion invocation operation (not the actual time it takes to really delete the repo) is very important for RHUI ops.  Sometimes a repo needs to be deleted and re-created to get rid of the repository version history and its associated artifacts.  More importantly, this performance is vital for the RHUI automation and CI during development.

**Comment by mdellweg** [comment]
I am convinced now, that repository delete should always be async. There's just too much going on to be executed in the gunicorn process.
