### ISSUE TITLE
As a user, I have a content guard that can authorize based on the contents of a base64 encoded json value in a header

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulpcore#4518]
**Is your feature request related to a problem? Please describe.**
Pulp users can perform authorization in their webserver, and then have the webserver send a header name and value to pulpcore-api and pulpcore-content. This header would be base64 encodedjson structure. The value to authorize on is some subpart of the json structure. [Here's an example](https://redhatinsights.github.io/insights-results-aggregator/authentication.html) of a structure like this (which we can also use as test data).

**Describe the solution you'd like**
Have a new content guard created which takes three parameters `header_name` and `json_accessor`, and `value`. For [this example](https://redhatinsights.github.io/insights-results-aggregator/authentication.html) you could create an instance of the content guard with `header_name='x-rh-identity'`, `json_accessor='.identity.internal.org_id'`, `value='3340851'`. Then any request with that header name and value set will be authorized.

For `json_accessor` I'm proposing we use [the `jq` syntax](https://jqlang.github.io/jq/manual/#basic-filters).

**Describe alternatives you've considered**
None

**Comment by jlsherrill** [comment]
This is  intended to support the X-rh-identity header within console dot.  This header value is actually a json struct, as an example:  https://redhatinsights.github.io/insights-results-aggregator/authentication.html

So for this to be generic, we'd need to express some sort of path into the struct to fetch the orgID value  "internal.org_id"

**Comment by dkliban** [comment]
So it sounds like this is a base64 encoded json token in a header. So we would need to know the header name, key_path, and expected value.

**Comment by bmbouter** [comment]
I revised the title and description based on the examples I heard here.

**Comment by decko** [comment]
Folks, do you think we should support the `jq` syntax entirely or just a simple parser to understand paths like the one in the example? (`.simple.path.without.complex.selectors`)

**Comment by bmbouter** [comment]
> Folks, do you think we should support the `jq` syntax entirely or just a simple parser to understand paths like the one in the example? (`.simple.path.without.complex.selectors`)

I looked around and found that [`pyjq`](https://github.com/doloopwhile/pyjq) would let us call jq syntax directly from python without subprocess. Specifically call it with the `one` call and catch the exception and deny authorization. This approach has a few benefits:

* It would let us tell users they can use whatever `jq` supports which from an expressability perspective would be good, e.g. users may need more complex parsing like accessing the third item of an array.
* It also allows us to stay out of the business of implementing/parsing the jq selector language itself which is good.

The downside is pulpcore will pick up more dependencies.

**Comment by mdellweg** [comment]
Yes for the library. If we were to install the jq binary we would need that library anyway. And calling subprocess inside an asgi request sounds scary.

**Comment by bmbouter** [comment]
> @bmbouter Would pulpcore have this dependency or just the plugin providing this content guard? (or would this guard be provided by core?) Trying to understand your comment

pulpcore would have the dependency. The current plan is to ship it in pulpcore.
