### ISSUE TITLE
Replicate a subset of repos at a time

### ISSUE THREAD

**Issue by PotentialIngenuity** [pulp/pulpcore#4539]
**Is your feature request related to a problem? Please describe.**
I would like to be able to replicate a subset of repos/distributions. 

**Describe the solution you'd like**
The replicate endpoint should take a list of repo/distribution names

**Describe alternatives you've considered**
N/A

**Additional context**
We have internal rpms that need to be pushed through different environments as fast as possible regardless of the status of the other repos.

**Comment by mdellweg** [comment]
Have you considered using labels and the build in labels_filter of the replicate feature?

**Comment by dkliban** [comment]
@PotentialIngenuity What @mdellweg was suggesting is that you apply `pulp_labels` to some distributions that you want to replicate. Then in your UpstreamPulp configuration use the 'pulp_label_select'[1] to only replicate distributions with that label. You can use the CLI to make these changes. 

[0] https://docs.pulpproject.org/pulp_rpm/restapi.html#tag/Distributions:-Rpm/operation/distributions_rpm_rpm_create
[1] https://docs.pulpproject.org/pulpcore/restapi.html#tag/Upstream-Pulps/operation/upstream_pulps_create

**Comment by ipanova** [comment]
closing per previous comment
