### ISSUE TITLE
Sync rpm files from AWS S3 bucket to pulp repository

### ISSUE THREAD

**Issue by raki-git** [pulp/pulpcore#4587]
**Is your feature request related to a problem? Please describe.**
Currently we are unable to sync rpm files that are in AWS S3 bucket to pulp repository

**Describe the solution you'd like**
I would like to have a feature that enable the sync tasks from AWS S3 bucket to pulp repository

**Describe alternatives you've considered**
As an alternative method I think we can either download the rpm files from AWS S3 bucket and upload them to pulp repository

**Comment by dkliban** [comment]
@raki-git Thanks for filing the issue. Can your yum/dnf clients already access this bucket? Is there repo metadata in the bucket?

**Comment by raki-git** [comment]
Thanks @dkliban for getting back to me. Yes the yum client have access to the bucket and it's just rpm files that are in the bucket (no repodata)

**Comment by ipanova** [comment]
if there is no repodata, it means that rpms will be stored in pulp as arbitrary files. is this what you are trying to achieve?

**Comment by raki-git** [comment]
Hi @ipanova There's repodata in the pulp repository but in the s3 bucket it's just rpm files that we have and we are just trying to sync those rpms from aws s3 bucket to a pulp repository. Currently we are manually downloading them(when we have a new rpm file) and upload it to s3 bucket.
i.e:
![image](https://github.com/pulp/pulpcore/assets/113863395/476169b9-fc34-44ff-93e5-acf65df0d2a9)

**Comment by dralley** [comment]
> Currently we are manually downloading them(when we have a new rpm file) and upload it to s3 bucket.

Wait, so do the RPMs start in the S3 bucket, or do you get them some other way, and then upload them to the S3 bucket?  

If it's the latter (which is what it sounds like?) then I'm not sure I understand the relevance of S3.  You could just upload them directly into Pulp, perhaps using the S3 backend for Pulp so that they are stored in the S3 bucket.

**Comment by raki-git** [comment]
Sorry @dralley my bad. Currently I'm manually downloading rpm files from s3 bucket and upload it to pulp repository (sorry in my previous comment I mistakenly typed `s3 bucket` it should be `pulp repository` that we are uploading in to.

**Comment by ipanova** [comment]
I see, so you want to skip the manual step to download and upload rpm files to pulp rpm repo and directly fetch rpms stored in the bucket into pulp rpm repo.

**Comment by ipanova** [comment]
There is pulpcore issue that would allow downloading artifacts https://github.com/pulp/pulpcore/issues/4608
However, the next steps would be plugin specific and would consist in making content( in this case rpm) and adding it to the rpm repo.

**Comment by gerrod3** [comment]
With the completion of #4608 you can now have Pulp create content from any url using the `file_url` field on the content create endpoint. https://pulpproject.org/pulp_rpm/restapi/#tag/Content:-Packages/operation/content_rpm_packages_create

I'm going to close the issue, if you want a greater ability to sync rpms from S3 I would suggest filing an issue in the pulp_rpm repository (https://github.com/pulp/pulp_rpm) with more details on the directory structure you would like to sync.
