### ISSUE TITLE
Unit tests for ChunkedFile

### ISSUE THREAD

**Issue by dralley** [pulp/pulpcore#4589]
Introduced here: https://github.com/pulp/pulpcore/pull/4541/

We should write a few unit tests for reading and seeking, and perhaps verifying.

**Comment by mdellweg** [comment]
Maybe when we do that we could make use of ChunkedFile for writing too.
Then we'd also have the bits nicely structured for unit testing.

**Comment by pedro-psb** [comment]
Hey @mdellweg,
Your idea of implementing a `write` method is to allow ChunkedFile to be tested without depending on a toc-file fixture?

If that the case, I believe a better approach would be not to [pass the toc-file](https://github.com/mdellweg/pulpcore/blob/5c4f9eace4daa9add10989fd855297b6e0bc5da6/pulpcore/app/tasks/importer.py#L71) in the first place. Instead, just passing the `files` (file list) and `chunk_size` should be enough to get it working and would make it more "unit-testable" (without introducing unnecessary behavior).
