### ISSUE TITLE
Add option to download artifacts using http/https

### ISSUE THREAD

**Issue by maartenbeeckmans** [pulp/pulpcore#4608]
**Is your feature request related to a problem? Please describe.**
The remote feature does not work with http directories on the internet as there is no standard on providing the metadata.

**Describe the solution you'd like**
An api endpoint where you can define a http link to a remote artifact and optionally a checksum and authentication options.

**Describe alternatives you've considered**
Another possibility to add artifacts now is downloading these locally with wget/curl, verifying the checksum and uploading it to pulp using the api.

**Chat about this topic**

@maartenbeeckmans
the main issue I have with the file plugin is that remotes not really work. The plugin expects a manifest file in a specific format which is not used by remote repos such as https://fedora.cu.be/linux/releases/37/Cloud/x86_64/images/ (which has the CHECKSUM file but different format) or https://cloud.debian.org/images/cloud/bullseye/20230124-1270/ (with the SHA512SUMS file which has another different format).
but this is a difficult topic as there is no standard to provide metadata like with rpm/deb

@dkliban
it sounds like you are interested in the file plugin being able to scrape an HTML page to discover what content is available

@gerrod3
Maarten Beeckmans: So when you want to request the file from Pulp, it would have the same relative-path on the upstream repo? If so file a feature request to add pull-through caching to pulp_file
or we could add what dkliban suggested and allow pulp_file to sync more repo types

@maartenbeeckmans
the same relative path is not really a requirement, it would be useful to just allow it to sync those repos so we don't have to do it manually

@dkliban
Maarten Beeckmans
Maarten Beeckmans: how do you do it now? do you scrape the HTML to discover the files?

@maartenbeeckmans
maybe add support for the filetype debian is using. It can be a possibility to add this to the remote, but that is just the output of the sha512sum command which is soms sort of standard (with support for other shasums)
but scraping seems difficult to implement correctly
but for me specifying this the file I want and a checksum to only download that content unit is also a valid option

@ggainey
also, scraping only works for upstream repos that enable directory-indexing - which more and more sites are disallowing

@gerrod3
ggainey: What are they doing instead? How would you find the files?

@ggainey
gerrod: consider rpm repos - there's "a" file at a known location, .../repo/repomd.xml, and you only "know about" files that repomd.xml tells you
a lot of content is intended to be used by applications that "know" what to look for - index.html is tehre to let human beings poke around
allowing directory-indexing tends to get flagged as apotential security exposure by a number of security-scanners these days
Maarten Beeckmans: I could see a, hrm, a "fetch Artifact" function in pulpcore, that would take a URL and an expected checksum, and try to fetch that content, verify its checksum, and create it as an Artifact.

@dkliban
ggainey: yeah ... as an alternative to upload

@ggainey
that functionality would also need to accept things like user/pwd, client-certs, proxy-setups - all the standard Remote auth-options

@dkliban
it could work in conjunction with a remote

@ggainey 
can we get a feature-request for this? then we can discuss implementation details in one place
dkliban: yeah
we want everything a Remote gives us, except it's not associated with a repository

@gerrod3 
if the client knows the url for the upstream repo then we can just implement pull-through caching for pulp_file

@ggainey 
gerrod: hrm, extending pulp_file to not-need a PULP_MANIFEST might work. But then there's no way for it to verify checksums
"point at this location on github" "ok - no manifest, so it's empty, but I can publish and dsitribute an empty file repo at /foo"  "wget <pulp>/foo/bar.txt" "ok, here it is. Hope it's what you wanted. I'm'a republish now"

@x9c4
What i see asked here (amongst other things) is some more file remotes that know how to enumerate files other than requiring a PULP_MANIFEST. e.g. sha256sums...

@gerrod3 
yeah that would be a nice feature. Is there an easy standard for declaring a parsing format? Maybe we can add a new field to the remote to pass on to the sync parser

@maartenb
but verifying the checksums is a requirement for mee, so the 'fetch artifact` function seems like a good idea

@dkliban 
Maarten Beeckmans: could you please file a feature request in Pulpcore to allow creating an artifact by having pulp download it nad verify checksum?

@ggainey 
^^ this, yes please
Maarten Beeckmans: you can even copy/paste today's discussion right into the issue

**Suggestions**

If this has been implemented it would be nice to also add this to other content plugin types as deb/rpm. There are a lot of projects out that publish their 'official' rpms/debs as github releases (thinking of https://github.com/cortexproject/cortex)

**Comment by ggainey** [comment]
From a triage-mtg conversation:  "this is 'add --url in addition to --file to the <foo> content create --repository bar command'"

**Comment by daviddavis** [comment]
Yea, I was imagining something like `pulp rpm content upload --url http://example.com/repos/test/test.rpm`.

**Comment by daviddavis** [comment]
There was some discussion about whether this was a separate feature or not. If it's a separate feature, I'm happy to file a new issue. Just let me know.

**Comment by MichalPysik** [comment]
I'm unassigning this issue for now to allow others to solve the issue, but plan to very possibly get back to it at the end of May. So far, here's how I think the appropriate serializer class should look like: https://github.com/pulp/pulpcore/pull/4362 .
