### ISSUE TITLE
Add ability to turn any Pulp instance into a replica

### ISSUE THREAD

**Issue by mchithu** [pulp/pulpcore#4637]
**Version**
Python PYPI installation
	PulpCore 3.32.0
	CertGuard 1.6.5
	file 1.14.4
	python 3.10.0
	rpm 3.22.3

**Describe the bug**
Replication task fails to maintain the publication attribute in a existing RPM distribution artifact. Instead it tries and fail to update the repository attribute in distribution artifact.

In a replication task group, I am getting a error for "general_update" task of a RPM distribution artifact
https://github.com/pulp/pulpcore/blob/main/pulpcore/app/tasks/base.py

ErrorDetail(string="Only one of the attributes 'repository' and 'publication' may used simultaneously.", code='invalid')

**To Reproduce**
In a upstream pulp server(Pulp1 server), create a repository with AutoPublish as false and it's distribution is based on Publications and repository field value is null.
In a downstream pulp server(Pulp2 server), do the same like create a repository with AutoPublish as false and it's distribution is based on Publications and repository field value is null.
Create a upstream object in Pulp2 server to replicate from upstream server (Pulp1 server)
Start the replication task in downstream pulp server(Pulp2 server) to replicate content from upstream server (Pulp1 server).
Replication task will fail to update the distribution artifact of the repository.

**Expected behavior**
Why Pulp replication doesn't replicate the publication from upstream pulp server when RPM repository distribution is based on publication.

**Comment by mdellweg** [comment]
This may still be a bug, but for the workflow, one is not supposed to create the repositories downstream by hand. Replicate is meant to handle _all_ of that.

**Comment by ipanova** [comment]
What does mean 'distribution is based on publication'? Does it mean that you have manually triggered publish task for the repo and then updated the distribution wth the created href of publication?

**Comment by dkliban** [comment]
@mdellweg I agree that the feature as currently designed requires the user to only use the replication API to create repositories/publications/distributions in the system. However, it would be better if you could use the replicate command to turn an existing Pulp installation into a replica with a single replicate task. The replicate task would need to be able to handle situations such as the one described in this issue. 

This is a request for a feature and not a bug.

**Comment by mchithu** [comment]
Hi,

Based on my knowledge I see this as a bug not as a feature request. Apologize, as I haven't provided an example. I'm doing this now.

In the Upstream server, we sync/add RPM packages to the repository and then publish the repository so distribution object is based on publication not by repository version.

` $ pulp rpm distribution list --name "rh-el7-extras"
{
  "pulp_href": "/pulp/api/v3/distribution/rpm/rpm/XXXXXXXXXXX",
  "pulp_created": "DATE",
  "base_path": "rh/el7/extras",
  "base_url": "Upstream Pulp Content Server Distribution URL",
  "content_guard": null,
  "hidden": false,
  "pulp_labels": {},
  "name": "rh-el7-extras",
  "repository": null,
  "publication: "/pulp/api/v3/publications/rpm/rpm/XXXXXXXXXXXX"
}`


Now I initiate a pulp replication task in the downstream server. The distribution object in downstream server is created based on repository attribute and not based on publication attribute.
`$ pulp rpm distribution list --name "rh-el7-extras"
{
  "pulp_href": "/pulp/api/v3/distribution/rpm/rpm/XXXXXXXXXXX",
  "pulp_created": "DATE",
  "base_path": "rh/el7/extras",
  "base_url": "Downstream Pulp Content Server Distribution URL",
  "content_guard": null,
  "hidden": false,
  "pulp_labels": {},
  "name": "rh-el7-extras",
  "repository": "/pulp/api/v3/repositories/rpm/rpm/XXXXXXXXXXXX",
  "publication: null
}`

**Comment by ipanova** [comment]
I see the confusion here, however, do you have any actual problem?

Rpm replicator task triggers MIRROR_COMPLETE sync, which automatically re-creates bit-by-bit publication. Then when content is served it makes sure to find publication serving the latest version https://github.com/pulp/pulpcore/blob/main/pulpcore/content/handler.py#L598

**Comment by ipanova** [comment]
Even though our Handler code seems to handle the serving of content, this not really intuitive https://github.com/pulp/pulpcore/blob/main/pulpcore/app/replica.py#L176
Maybe replica code should take into account publications and set them for the publication based distributions? @dkliban you have any insights here?

**Comment by mchithu** [comment]
> I see the confusion here, however, do you have any actual problem?
> 
> Rpm replicator task triggers MIRROR_COMPLETE sync, which automatically re-creates bit-by-bit publication. Then when content is served it makes sure to find publication serving the latest version https://github.com/pulp/pulpcore/blob/main/pulpcore/content/handler.py#L598

Yes, I am facing a problem. In our setup, the role of upstream and downstream is swapped. During the maintenance window of the upstream server, one of the existing downstream servers will be promoted as upstream server and start supplying comtent to rest of the downstream servers.

At this time in the downsteam server (whose role is due to change to upstream), I have destroy all distribution artifacts and recreate them based on publication attribute and keep repository attribute as null.

**Comment by ggainey** [comment]
To clarify, based on recent pulpcore mtg to discuss: The ask here, is for the replication code to notice this problem, and for the replication to "win" (ie reset/'fix' the downstream to be 'replicable') instead of failing.  

Should be a straightforward fix, and easy to have test cases for.
