### ISSUE TITLE
file:// sync deletes files from directory

### ISSUE THREAD

**Issue by ianballou** [pulp/pulpcore#4681]
**Version**
Pulpcore 3.39

**Describe the bug**
When syncing file:// repositories, files are disappearing after the sync.

**To Reproduce**
1) Copy these two repositories to the FS:
  - https://github.com/Katello/katello/tree/master/test/fixtures/test_repos/file1
  - https://github.com/Katello/katello/tree/master/test/fixtures/test_repos/file2
2) Sync one, then the other
3) See that some files disappeared.
  - In my case, file2 lost every file except PULP_MANIFEST

**Expected behavior**
No files disappear.

**Additional context**
This also occurred with RPM content type files.

**Comment by ianballou** [comment]
Likely related to https://github.com/pulp/pulpcore/pull/4428

**Comment by ianballou** [comment]
A repeat of https://pulp.plan.io/issues/9146 ?

**Comment by dralley** [comment]
CI is complaining that the issue is closed

**Comment by dralley** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2249847
