### ISSUE TITLE
pulp-file 1.15.1 requires pulpcore 3.39.1

### ISSUE THREAD

**Issue by pete-scrutton** [pulp/pulpcore#4696]
I have installed pulp-rpm 3.24.0 which requires pulpcore 3.40.3
but pulp-file 1.15.1 requires pulpcore 3.39.1

has pulp-file been updated to "resolve" this conflict?

**Comment by lubosmj** [comment]
This seems to be already resolved, can we close it, @mdellweg?

**Comment by mdellweg** [comment]
Yes this is solved.
