### ISSUE TITLE
Broken link: plugin writing points to old pulp_file

### ISSUE THREAD

**Issue by KevinMGranger** [pulp/pulpcore#4765]
[On the index for the plugin writer's guide](https://docs.pulpproject.org/pulpcore/plugin_dev/plugin-writer/index.html#:~:text=Along%20with%20this%20guide%2C%20it%20may%20be%20useful%20to%20refer%20to%20to%20our%20simplest%20plugin%2C%20pulp_file.), `pulp_file` links to the [pulp_file repository](https://github.com/pulp/pulp_file/tree/main). But since it's been merged into pulpcore, it should likely link to [./pulp_file](https://github.com/pulp/pulpcore/tree/d5332d197f48d2bd3b5253e6ad71818f7a3b4d76/pulp_file) in this repository.

**Comment by gerrod3** [comment]
Closed as we moved to the unified site: https://pulpproject.org
