### ISSUE TITLE
Add a "updated" date to a distribution

### ISSUE THREAD

**Issue by mimmus** [pulp/pulpcore#5033]
As a rpm packages repos administrator for a company, I manage updates lifecycle like this:

* sync repo with remote
* create a new publication version
* update "DEV" distribution, to point to new version
* apply updates to DEV machines and wait for some time
* update "QA" distribution to point on the same version of "DEV"
* apply updates to QA machines...
* etc

and I'd like to know _when_ I moved forward an environment

**Additional context**
Actually, only "pulp_created" is available on a distribution and this date is not updated when I update the distribution to point to a newer publication version.

**Comment by ipanova** [comment]
We have also `pulp_last_updated` field we just need to serialize it

```
In [7]: disto.__dict__
Out[7]: 
{'_state': <django.db.models.base.ModelState at 0x7fddb1418580>,
 'pulp_id': UUID('018bda21-e2e5-711e-9c68-3860678d21ee'),
 'pulp_created': datetime.datetime(2023, 11, 16, 21, 55, 35, 782730, tzinfo=datetime.timezone.utc),
 'pulp_last_updated': datetime.datetime(2023, 11, 16, 21, 55, 35, 782747, tzinfo=datetime.timezone.utc),
```

**Comment by mimmus** [comment]
Thank you!
