### ISSUE TITLE
pulpcore python library does not support API_ROOT

### ISSUE THREAD

**Issue by ReLehmann** [pulp/pulpcore#5130]
**Version**
pulpcore 3.49.0
pulpcore-client 3.49.0

**Describe the bug**
Custom API roots are currently not supported due to hard coded URL paths.

**To Reproduce**
```bash
python -m venv .venv
source .venv/bin/activate
pip install pulpcore pulpcore-client
grep -R "/pulp/api/" .venv
```

**Expected behavior**
Support of API_ROOT configurations

**Comment by gerrod3** [comment]
Can you be specific which files you are seeing that are using hard coded paths? I am not seeing any files besides our docs when running `grep` on my dev machine.

**Comment by ReLehmann** [comment]
Interesting, examples from my .venv: 

`.venv/lib/python3.12/site-packages/pulpcore/client/pulpcore/api/remotes_api.py` 

from line 267
```python
        return self.api_client.call_api(
            '/pulp/api/v3/remotes/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PaginatedRemoteResponseList',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
```

**Comment by gerrod3** [comment]
You are right, I missed the `pulpcore-client` in your pip command. This is a know issue in our client libraries, they are published assuming using the default `API_ROOT`. Currently the only way around this is to manually generate them yourself with your correct `API_ROOT`: https://github.com/pulp/pulp-openapi-generator?tab=readme-ov-file#generating-bindings-against-re-rooted-systems

**Comment by mdellweg** [comment]
When you are about to implement something new, please consider using pulp-glue instead (If it's something existing, consider migrating). The bindings are autogenerated and not guaranteed to be useful when not generated for your specific installation. Glue uses some other mechanisms to work around this kind of issues.

https://docs.pulpproject.org/pulp_cli/glue_reference/common_openapi/

**Comment by ReLehmann** [comment]
Thanks for the advice, we will implement them. 👍
