### ISSUE TITLE
Better error information than 'Server got itself in trouble' for status 500 pages

### ISSUE THREAD

**Issue by abctaylor** [pulp/pulpcore#5239]
Hi - it's quite tricky to debug Pulp when the 500 status errors are so minimal (and the logs in the operator pod are just python stack traces). Could it be proposed to make something more useful show here?

![image](https://github.com/pulp/pulp-operator/assets/30197206/173f4856-22f1-4ffa-b3b7-e6ae61a4f90d)

**Comment by dkliban** [comment]
In case of a 500 error, we are not able to provide anything more helpful for the user.
