### ISSUE TITLE
Ability to filter packages by added/removed between two repository versions

### ISSUE THREAD

**Issue by adrianabedon** [pulp/pulpcore#5241]
Currently, pulp supports filtering packages by if they were added or removed since a repository version with the `repository_version_added` and `repository_version_removed` parameters. Extending this to support filtering packages by if they were added or removed between two repository versions would accelerate our server where we need this information. For example, a request to pulp with `repository_version_added=repoversion1,repoversion2` would list packages that were not in `repoversion1` but in `repoversion2`.

**Comment by mdellweg** [comment]
The "q" filter can be used to combine the existing content filters.
