### ISSUE TITLE
Add SFTP backend support for domains

### ISSUE THREAD

**Issue by gerrod3** [pulp/pulpcore#5255]
Enable SFTP backend support for domains, the serializer is already written: https://github.com/pulp/pulpcore/blob/main/pulpcore/app/serializers/domain.py#L89  Add a warning on the choice that reflects the current state of SFTP to the user: https://github.com/pulp/pulpcore/blob/main/pulpcore/app/serializers/domain.py#L18, https://docs.pulpproject.org/pulpcore/installation/storage.html#sftp

**Comment by dkliban** [comment]
Let's deprecate SFTP support in pulp in general.
