### ISSUE TITLE
requirements.txt backports requested

### ISSUE THREAD

**Issue by ggainey** [pulp/pulpcore#5341]
Downstream user has requested backports to core/3.28 for the following, to allow CVE fixes to our dependencies:

- **aiohttp-3.9.4** - should use https://github.com/pulp/pulpcore/pull/5270 , already backported to 3.49, allows 3.9.5
- **crypography-42.0.4** - should use https://github.com/pulp/pulpcore/pull/5330 to allow up to 42.0.7
- **jinja-3.1.4** - should use https://github.com/pulp/pulpcore/pull/5327

The backport-machinery generally fails on requirements.txt due to conflicts, so this should be manual PRs submitted for the following versions to keep everything in sync:

- 3.28
- 3.39
- 3.49
- 3.53

Should be merged prior to 14-MAY-2024 releases.

**Comment by gerrod3** [comment]
Is this issue finished, can it be closed?

**Comment by ggainey** [comment]
> Is this issue finished, can it be closed?

Checking requirements.txt in the requested branches shows all the requewsted changes - closing
