### ISSUE TITLE
Issues with self-signed Certificates on pulp base-images using EL9

### ISSUE THREAD

**Issue by decko** [pulp/pulpcore#5406]
**Describe the bug**
All branches using the EL9 based base-image are failing on tests with self-signed certificate errors.

https://github.com/pulp/pulpcore/actions/runs/9171331320/job/25229329542?pr=5397#step:14:965
https://github.com/pulp/pulpcore/actions/runs/9171339489/job/25229254490?pr=5402#step:14:1800

as examples.

**Comment by ggainey** [comment]
Fixed by https://github.com/pulp/plugin_template/commit/df91f7970532656e531e57afa79509388b2e4fe9
