### ISSUE TITLE
Pulp replication should leverage optimsations to significantly improve performance

### ISSUE THREAD

**Issue by PaulUrwin** [pulp/pulpcore#5493]
**Is your feature request related to a problem? Please describe.**
At the moment Pulp replication is not particularly quick, it can take several minutes for it to identify that in fact there are no changes necessary.   Because it spends so much effort trying to make this determination, this clogs up the workers from doing the important work of actually syncing what has changed (say 1 repo out of hundreds), this in turn can lead to an increasing backlog of requested replications, which significantly slows down Pulp competing any given replication request.

**Describe the solution you'd like**
Instead of Pulp spending time checking repodata of every repository, it should instead just use the distributions API on the main host to see which distributions have a last modified timestamp newer than when the last replication took place.  This should allow it to make a determination of which repos actually require repodata examination pretty much instantaneously, and only then kick off tasks for checking those repositories that have actually changed, if indeed any have.

**Describe alternatives you've considered**
We can help reduce the number of replication requests sent to Pulp by checking if there's already pending replication task groups that have not started running, however this will still lead to lower performance than we would like, we'd like to be able to say quickly that a package added to a repository is available everywhere, so that activities such as user self-service management of repositories through our application feels responsive.

**Additional context**
@bmbouter  and I chatted about this yesterday.

**Comment by bmbouter** [comment]
Thanks @PaulUrwin for filing.

I think we could make this better by having the replica Pulp for each distribution from the remote Pulp record the pulp_last_updated time. If that timestamp changes, or it's None (meaning never been sync'd) only then create a task in the task group to sync it.

**Comment by gerrod3** [comment]
The check will have to be a bit more complicated then `pulp_last_updated` time. If your upstream distro is using auto-publish then the distro doesn't get updated when a new repo-version is created. You have to look one layer in to see if the upstream backing repository or publication is newer then the replica's latest repo-version.

**Comment by lubosmj** [comment]
There is one limitation to this approach. If a user attaches a repository to a distribution, content-app will serve data from the publication of the latest available repository version: https://github.com/pulp/pulpcore/blob/734335fbcfb5420caf455f4faa2e428e202bf8d1/pulpcore/content/handler.py#L601-L616

This is the behaviour I am seeing; though, I cannot find any code that enforces the lookup ordering for the latest repository version. If I create a new publication for an older repository version, it is not picked up by the distribution. It goes for the latest repository version. If I remove the publication for the latest repository version, it picks up the publication for the older repository version.

--------------------------------------------------------------

1. Creating a publication for the version 1
```
http :8080/pulp/api/v3/publications/file/file/ repository_version=/pulp/api/v3/repositories/file/file/0190eea6-b3fb-71c1-9f73-f3c569175876/versions/1/
```
```
http :8080/pulp/content/test/
```
```
<html>
<head><title>Index of /pulp/content/test/</title></head>
<body bgcolor="white">
<h1>Index of /pulp/content/test/</h1>
<hr><pre><a href="../">../</a>
<a href="1.iso">1.iso</a>                                                                                               26-Jul-2024 10:47  1.0 kB
<a href="2.iso">2.iso</a>                                                                                               26-Jul-2024 10:47  1.0 kB
<a href="3.iso">3.iso</a>                                                                                               26-Jul-2024 10:47  1.0 kB
<a href="PULP_MANIFEST">PULP_MANIFEST</a>                                                                                       29-Jul-2024 08:23  228 Bytes
</pre><hr></body>
</html>
```

2. Creating a publication for the version 2
```
http :8080/pulp/api/v3/publications/file/file/ repository_version=/pulp/api/v3/repositories/file/file/0190eea6-b3fb-71c1-9f73-f3c569175876/versions/2/
```
```
http :8080/pulp/content/test/
```
```
...
<a href="98.iso">98.iso</a>                                                                                              26-Jul-2024 12:25  1.0 kB
<a href="99.iso">99.iso</a>                                                                                              26-Jul-2024 12:25  1.0 kB
<a href="PULP_MANIFEST">PULP_MANIFEST</a>                                                                                       29-Jul-2024 08:23  19.4 kB
</pre><hr></body>
</html>
```
3. Deleting the publication for the version 2 (distributing the version 1 now)
```
http DELETE :8080/pulp/api/v3/publications/file/file/0190fd96-8606-773c-8f86-2d13032be92e/
```
```
http :8080/pulp/content/test/
```
```
<html>
<head><title>Index of /pulp/content/test/</title></head>
<body bgcolor="white">
<h1>Index of /pulp/content/test/</h1>
<hr><pre><a href="../">../</a>
<a href="1.iso">1.iso</a>                                                                                               26-Jul-2024 10:47  1.0 kB
<a href="2.iso">2.iso</a>                                                                                               26-Jul-2024 10:47  1.0 kB
<a href="3.iso">3.iso</a>                                                                                               26-Jul-2024 10:47  1.0 kB
<a href="PULP_MANIFEST">PULP_MANIFEST</a>                                                                                       29-Jul-2024 08:23  228 Bytes
</pre><hr></body>
</html>
```

So, if a user decides to delete a publication, we should reflect this within the optimization. I wonder if we can ignore this. If not, we need to traverse publications and their timestamps, and the numbers of versions they are attached to in order to correctly determine whether the distribution has been "updated" or not.
```
http :8080/pulp/api/v3/publications/file/file/?repository=/pulp/api/v3/repositories/file/file/0190eea6-b3fb-71c1-9f73-f3c569175876/
```

**Comment by lubosmj** [comment]
We will need to store the information about the last used publication.
