### ISSUE TITLE
Users with no permissions can upload Artifacts to Pulp

### ISSUE THREAD

**Issue by lubosmj** [pulp/pulpcore#5525]
**Describe the bug**
Users with no permissions can upload artifacts to Pulp using the `/pulp/api/v3/artifacts/` endpoint. We advocate for restricting the access to this endpoint. Only admins should be able to upload raw artifacts to Pulp.

**To Reproduce**
```
pulp user create --username user --password krokodyl1 --email user@test.com
echo "wow" > testhello.txt
http --form POST :5001/pulp/api/v3/artifacts/ file@./testhello.txt -a user:krokodyl1
```
```
HTTP/1.1 201 Created
Access-Control-Expose-Headers: Correlation-ID
Allow: GET, POST, HEAD, OPTIONS
Connection: keep-alive
Content-Length: 679
Content-Type: application/json
Correlation-ID: 1ff96fae07da4d05b8ed8feaa21f9c5c
Cross-Origin-Opener-Policy: same-origin
Date: Tue, 25 Jun 2024 13:02:31 GMT
Location: /pulp/api/v3/artifacts/01904f7d-a0c3-72cb-bb93-1342a39f7cb4/
Referrer-Policy: same-origin
Server: nginx/1.22.1
Vary: Accept
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "file": "artifact/f4/0cd21f276e47d533371afce1778447e858eb5c9c0c0ed61c65f5c5d57caf63",
    "md5": null,
    "pulp_created": "2024-06-25T13:02:31.620056Z",
    "pulp_href": "/pulp/api/v3/artifacts/01904f7d-a0c3-72cb-bb93-1342a39f7cb4/",
    "pulp_last_updated": "2024-06-25T13:02:31.620076Z",
    "sha1": null,
    "sha224": "8428b309ef4017df9b29d26a81771d320d3bff61404c9d0296609d16",
    "sha256": "f40cd21f276e47d533371afce1778447e858eb5c9c0c0ed61c65f5c5d57caf63",
    "sha384": "1c06d0e58db38d4d250db07a15f6a8ef40263dc25f95c0890f1ee0ddd396c2d1dca17dccefcba4a6df4a9d99327fd8e2",
    "sha512": "d7cc8802241aa6927a82ddfa7386977858a1e3f31c72db260935b89c33cf26e92939a3a15b0bf80adc5ecf6b9b63ef09843f4e0631ba8b5841996e26eae5e92b",
    "size": 4
}

```

**Expected behavior**
A permission error raised (403).

**Comment by lubosmj** [comment]
It is worth investigating if other "admin" endpoints are affected too.

**Comment by gerrod3** [comment]
It's because the artifact viewset uses a different permission class from our default. 
https://github.com/pulp/pulpcore/blob/bd374a351406621aec0c042418795b5ab37cbe1d/pulpcore/app/viewsets/content.py#L76
Apparently this has been a feature for a while, 3 years. (https://github.com/pulp/pulpcore/commit/c600ff1b63ea45e6020d980736f2f749b76e8be8) Thinking about it, our cli would probably break if we change the upload behavior. The delete behavior probably should be protected though.

**Comment by mdellweg** [comment]
The cli uses the content creation from uploads where applicable.
So that should be fine.
Also artifact destroy should never ever have been there. orphan cleanup _must_ be the only codepath to delete artifacts.

**Comment by 514amir** [comment]
I have a similar issue where I use repository file content upload then I want to create an entry with a different name but the same underlying in the same repos

Unless I was an admin no combination of permissions and commands would make it work, I resulted to having to upload the file twice with different relative_paths

file content create
repository file content add 
etc...
