### ISSUE TITLE
Allow renaming of roles (or anything with an update option and a href identifier to change it's name)

### ISSUE THREAD

**Issue by simenon** [pulp/pulpcore#5542]
**Is your feature request related to a problem? Please describe.**
I had a typo in the role name. In the current working i had to delete it and recreate it

**Describe the solution you'd like**
Allow role update with a href to change the name of the role

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by simenon** [comment]
I did not check through the API but with the pulp-cli and through the pulp-cli you can not change the name of the role.

**Comment by lubosmj** [comment]
Ooops. 🙈 Yes, you are right. After experimenting a bit with this, I noticed that you cannot update a name of literally any resource with pulp-cli. That is probably caused by the way how we look-up resources in general.

@mdellweg, do you think we should open an issue against pulp-cli to allow updating names of resources?

**Comment by lubosmj** [comment]
@simenon, for now, I suggest you to use the API to accomplish this task. You can use [`httpie`](https://httpie.io/docs/cli/installation) to do that:
```
http :5001/pulp/default/api/v3/roles/0190bc9c-1e26-7de9-b75e-eab4c599c753/
```
```
{
    "description": "best role ever",
    "locked": false,
    "name": "test",
    "permissions": [],
    "pulp_created": "2024-07-16T17:34:26.343299Z",
    "pulp_href": "/pulp/default/api/v3/roles/0190bc9c-1e26-7de9-b75e-eab4c599c753/",
    "pulp_last_updated": "2024-07-16T17:34:26.343326Z"
}
```

```
http PATCH :5001/pulp/default/api/v3/roles/0190bc9c-1e26-7de9-b75e-eab4c599c753/ name=testtesttest333
```
```
{
    "description": "best role ever",
    "locked": false,
    "name": "testtesttest333",
    "permissions": [],
    "pulp_created": "2024-07-16T17:34:26.343299Z",
    "pulp_href": "/pulp/default/api/v3/roles/0190bc9c-1e26-7de9-b75e-eab4c599c753/",
    "pulp_last_updated": "2024-07-16T17:43:19.992254Z"
}


```

**Comment by mdellweg** [comment]
Well, you basically captured it well. The name is an identifier for the object. And changing and identifier is an action where you should pause and think twice. At this point I'm at it's possible vie an api call if you know what you are doing and you better be aware of the consequences, but we will not likely implement it in the cli.
