### ISSUE TITLE
Breaking changes in 3.49.14 Ruby bindings

### ISSUE THREAD

**Issue by ianballou** [pulp/pulpcore#5592]
**Version**
Pulpcore 3.49.14 (specifically the bindings)

**Describe the bug**
Some bindings methods were renamed. Examples:
PulpCertguardClient::ContentguardsRhsmApi.list turned into contentguards_certguard_rhsm_list
PulpcoreClient::TasksApi.read turned into tasks_read

**To Reproduce**
Try using a `read` method on the Pulpcore tasks API. It  doesn't exist as of 3.49.14.

**Expected behavior**
A z-stream update shouldn't rename API methods.

**Additional context**
Should Katello pin back to 3.49.13, or can it be fixed soon in a 3.49.15?

**Comment by evgeni** [comment]
The diff is huge: https://my.diffend.io/gems/pulpcore_client/3.49.13/3.49.14/page/2

**Comment by ianballou** [comment]
@evgeni nice find.  Katello has pinned to be below 3.49.13 temporarily.

**Comment by evgeni** [comment]
Could any of the changes done in https://github.com/pulp/pulp-openapi-generator/pull/91 have influence on the result?

**Comment by evgeni** [comment]
3.55.1 to 3.55.2 has the same issue :/

**Comment by mdellweg** [comment]
This sounds like the missing of `&bindings` when asking for the api.json.
We need to create a really badly broken version of the api spec to generate these "nice" bindings.

**Comment by mdellweg** [comment]
https://github.com/pulp/plugin_template/pull/894

I think, this should solve it. We were building the ruby bindings from the wrong spec.

**Comment by evgeni** [comment]
@mdellweg should the affected releases be yanked?

**Comment by ianballou** [comment]
Yanking the gems would be helpful so we don't need to add exceptions in our requirements for those releases.

**Comment by mdellweg** [comment]
Do we know which ones are affected?
Let me start a list here, please add any known gems.

Released gems to yank:
- [ ] pulpcore-client 3.49.14

**Comment by ggainey** [comment]
pulpcore_client/3.39.18, 3.49.14, and 3.55.2 have all been yanked.

**Comment by lubosmj** [comment]
Can we also yank pulp_container_client 2.20.1?

**Comment by ggainey** [comment]
> Can we also yank pulp_container_client 2.20.1?

Done

**Comment by ianballou** [comment]
It looks like this issue might also affect older gem clients. We just saw the bug happen on the 2.14 branch of pulp container client, but we're unsure which version introduced it.
