### ISSUE TITLE
Re-enable Storage Metrics

### ISSUE THREAD

**Issue by decko** [pulp/pulpcore#5762]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by bmbouter** [comment]
At the pulpcore meeting today we identified a design we want to try:

1. Use a TaskSchedule (as is, no arguments)
2. Have that task run every 5 minutes
3. Have that 1 task report on all domains
