### ISSUE TITLE
Run immediate tasks in the parent process of the worker

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#5767]
**Is your feature request related to a problem? Please describe.**
Immediate tasks, such as updates of repositories, remotes, and distributions can get stuck behind long running tasks such as syncs and publish.

**Describe the solution you'd like**
Have the parent process of the worker execute the immediate tasks in the parent process itself when all the resources for the task are available.

**Comment by pedro-psb** [comment]
I'm taking this with @mdellweg mentorship

**Comment by pedro-psb** [comment]
We designed a plan to implement this in three steps for smoother deliver and feedback cycles:
1) Prioritize immediate task
2) Add special handler to immediate task (run in foreground + timeout)
3) We'll discuss more (can't remember right now :sweat_smile: )

**Comment by mdellweg** [comment]
4. Rewrite the pulpcore-worker in python async.
  - We are halfway there already with the select looping, and keeping the heartbeat loop responsive while performing lot's of immediate tasks would be made much easier with proper async.
