### ISSUE TITLE
Add support for arguments to a TaskSchedule instance

### ISSUE THREAD

**Issue by decko** [pulp/pulpcore#5778]
**Is your feature request related to a problem? Please describe.**
When scheduling a task you're not able to set a domain to which this task would run.
Also, you're not able to set the arguments for the schedule task to run.

Being able to define those things would allow you to schedule and filter scheduled tasks for a given domain
and set arguments that may be needed to run the task would help on its usage.

**Comment by bmbouter** [comment]
At the pulpcore meeting we identified we do not need arguments for a use case at this time. We can reopen later if we do at that time.
