### ISSUE TITLE
Plugin API docs are not properly rendered

### ISSUE THREAD

**Issue by dkliban** [pulp/pulpcore#5834]
Went to look at this page and realized it wasn't rendering the content properly 

https://pulpproject.org/pulpcore/docs/dev/reference/code-api/plugins-api/util/

**Comment by pedro-psb** [comment]
That's the right place. We use the mkdocstrings plugin for that, so it should follow it's syntax:
https://mkdocstrings.github.io/usage/

**Comment by clintonsteiner** [comment]
Appears to be fixed now?
