### ISSUE TITLE
Reclaim space bash example is not shown correct in documentation

### ISSUE THREAD

**Issue by simenon** [pulp/pulpcore#5876]
The BASH example at https://pulpproject.org/pulpcore/docs/user/guides/reclaim-disk-space/?h=artifact does not render correctly

![image](https://github.com/user-attachments/assets/d1e1112d-e393-49f9-ab6e-618bd4ef1ae5)

**Comment by lubosmj** [comment]
@simenon, would you mind contributing the fix? You can find the doc here: https://github.com/pulp/pulpcore/blob/cd2b35fdfa87a45df8722f37cb8a1b6a8d34abc1/docs/user/guides/reclaim-disk-space.md?plain=1#L14. It should have the structure similar to https://github.com/pulp/pulpcore/blob/cd2b35fdfa87a45df8722f37cb8a1b6a8d34abc1/docs/user/guides/create-domains.md?plain=1#L59, without (`j` and with an empty line).

**Comment by simenon** [comment]
https://github.com/pulp/pulpcore/pull/5877
