### ISSUE TITLE
Task metrics reporting an incorrect number of unblocked tasks

### ISSUE THREAD

**Issue by decko** [pulp/pulpcore#5941]
**Describe the bug**
If a number of unblocked tasks are in the "complete state", like `canceled` or `failed`, somehow they will be showed in the task metrics, leading to some confusing conclusions.

**To Reproduce**
Create some tasks with different exclusive resources, like different `domain`. Make them fail, or cancel them.
It's gonna show a number of unblocked tasks waiting in the queue, which is not true.

**Expected behavior**
It's  expected to only show unblocked tasks that are waiting in the queue to be executed.

**Comment by pedro-psb** [comment]
It's possible that there is some weird orm/sql interaction there (like this [filter that yields more result than the original](https://github.com/pulp/pulpcore/pull/3642)). The aggregation docs warns about [doing aggregations with multiple tables](https://docs.djangoproject.com/en/5.1/topics/db/aggregation/#combining-multiple-aggregations), but it doesnt seem the case here. We should analyze the SQL to see if we can sport anything weird.

Or it could be some curious timining hazard.

**Comment by decko** [comment]
We found some tasks when querying the database @pedro-psb. Strangely they were lying there with the `unblocked_at` field, and also at the `COMPLETE_STATE`. Most of them were failing tasks, but some were canceled ones.

**Comment by pedro-psb** [comment]
And they also had the `started_at=Null`?
https://github.com/pulp/pulpcore/blob/c126e77a7ea6e2a19a78c34c53defda0697d1743/pulpcore/tasking/worker.py#L482-L495
