### ISSUE TITLE
Renaming Remote + Resync can lead to leftover RemoteArtifacts

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulpcore#5968]
**Describe the bug**
When we have a Remote with url $A$, sync, change it to $B$, and resync (having the respective Remote servers change urls too), Pulp will have leftover RemoteArtifact with url = $A$ (the old one).

**To Reproduce**
* Create a Remote with url $A$ and sync
* Change it to $B$ (and also the remote server url) and resync
* Query for RemoteArtifacts containing url= $A$.

**Expected behavior**
On the event a Remote.url is changed, Pulp should delete (or update?) it's related RemoteArtifacts.

**Additional context**
That was observed in a Satellite bug report on our slack channel. Related: https://github.com/pulp/pulpcore/issues/5967

**Comment by ipanova** [comment]
I had an impression that we do update existing RA with new url https://github.com/pulp/pulpcore/blob/6b066da9a98690fd5f7639c2089ef65ca32869b8/pulpcore/plugin/stages/artifact_stages.py#L446

**Comment by dralley** [comment]
RemoteArtifacts are unique by (remote, contentartifact, domain).  So if you change the URL on a Remote, I don't think you can end up with a new RemoteArtifact, because you can only have one per remote.

So I would expect it would have to update the existing one.

**Comment by pedro-psb** [comment]
Pulp does handle the remote renaming properly. The reproducer in the description does not hold.
Something else caused the leftover on the satellite case, maybe in the host rename script (or elsewhere, who knows).
