### ISSUE TITLE
After deleting a pypi repo - storage stays at the same level as before

### ISSUE THREAD

**Issue by mikch06** [pulp/pulpcore#6052]
I did a pypi synch. But removed it again because of other usage.
No - storage usage stays the same. 

I think its not the package space - but the database.
Is it possible to cleanup the database and remove old entries?

**Comment by gerrod3** [comment]
It depends, if you deleted the repository and the packages are not in any other repositories, i.e. they're orphans, then you can run orphan cleanup and it will remove those packages and their corresponding database entries.

CLI command:
`pulp orphan cleanup --protection-time 0`

If you want to just remove the package artifacts, but keep the database entries, i.e turn them into on-demand artifacts, then you can use reclaim. Note the packages have to be in a repository for this command to work, it doesn't work on orphans.

CLI command:
`pulp repository reclaim --repository repo_name  # or you can use --all`

**Comment by mikch06** [comment]
Great, thx a lot!
'reclaim' helped!!

Repository is already gone, but with --all i dould do it.

Thank you.
