### ISSUE TITLE
Custom settings not propogating

### ISSUE THREAD

**Issue by tustvold** [pulp/pulpcore#81]
I'm trying to configure the S3 storage backend, however, am running into an issue with settings not propogating correctly.

I have set `DJANGO_SETTINGS_MODULE` to `pulpcore.app.settings` as an environment variable, and additionally have set `PULP_SETTINGS` to `/var/lib/pulp/settings.yaml` which is where I have set the variables. The templated contents of which are below:

```
default:
  # Django
  SECRET_KEY: '${PULP_SECRET}'
  DEBUG: True

  CONTENT_HOST: '${CONTENT_HOST}'

  # Redis
  REDIS_HOST: '${REDIS_HOST}'
  REDIS_PORT: ${REDIS_PORT}
  REDIS_PASSWORD: '${REDIS_PASSWORD}'

  # Storage
  AWS_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID}'
  AWS_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
  AWS_STORAGE_BUCKET_NAME: '${S3_STORAGE_BUCKET_NAME}'
  AWS_DEFAULT_ACL:
  AWS_AUTO_CREATE_BUCKET: False

  DEFAULT_FILE_STORAGE: storages.backends.s3boto3.S3Boto3Storage
  MEDIA_ROOT:  ''

  # Postgres
  DATABASES:
    default:
      CONN_MAX_AGE: 0
      ENGINE: django.db.backends.postgresql_psycopg2
      NAME: '${PGSQL_DB}'
      USER: '${PGSQL_USER}'
      PASSWORD: '${PGSQL_PASSWORD}'
      HOST: '${PGSQL_HOST}'
      PORT: ${PGSQL_PORT}
```

The problem appears to be that [pulpcore.app.settings](https://github.com/pulp/pulpcore/blob/master/pulpcore/app/settings.py#L20) is following the explicit approach as described [here](https://github.com/rochacbruno/dynaconf/blob/master/docs/guides/django.md#explicit-mode) but is missing the crucial `settings.populate_obj(sys.modules[__name__])`. This means that **only** the settings explicitly mentioned in the file are propogated.

*Caveat: I am new to django and dynaconf so might be missing something incredibly obvious*

**Comment by bmbouter** [comment]
@tustvold we would love to help. Unfortunately this issue tracker is open by mistake and I'm about to close it. This would also be a great question for pulp-list, would you mind re-asking there?

https://pulpproject.org/help/#mailing-list

You might also consider coming into IRC (links on the website there also) for some synchronous help.
